!define SITECORE_COLOR #EB001A


'cdp.puml
sprite $cdp [64x64/16] {
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAABBBBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA6555AAAAAAAAAAA
AAAAAAAAAAABBBBBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA55555AAAAAAAAAAA
AAAAAAAAAABBBBBBBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA6555555AAAAAAAAAA
AAAAAAAAABBBBBBBBBAAAAAAAAAAAAAAAAAAAAAAAAAAAA555555555AAAAAAAAA
AAAAAAAABBBBBBBBBBBAAAAAAAAAAAAAAAAAAAAAAAAAA65555555559AAAAAAAA
AAAAAAAABBBBBBBBBBBBAAAAAAAAAAAAAAAAAAAAAAAA555555555555AAAAAAAA
AAAAAAABBBBBBBBBBBBBBAAAAAAAAAAAAAAAAAAAAAA65555555555555AAAAAAA
AAAAAAABBBBBBBBBBBBBBAAAAAAAABBBBBBAAAAAAAA55555555555555AAAAAAA
AAAAAAABBBBBBBBBBBBBBAAAAABBBBBBBBBBBBAAAAA55555555555555AAAAAAA
AAAAAABBBBBBBBBBBBBBBAAAABBBBBBBBBBBBBBAAAA555555555555555AAAAAA
AAAAAABBBBBBBBBBBBBBAAAABBBBBBBBBBBBBBBBAAAA55555555555555AAAAAA
AAAAAABBBBBBBBBBBBBBAAABBBBBBBBBBBBBBBBBBAAA55555555555555AAAAAA
AAAAABBBBBBBBBBBBBBAAAABBBBBBBBBBBBBBBBBBBAAA55555555555555AAAAA
AAAAABBBBBBBBBBBBBBAAABBBBBBBBBBBBBBBBBBBBAAA55555555555555AAAAA
AAAAABBBBBBBBBBBBBBAABBBBBBBBBBBBBBBBBBBBBBAAA5555555555555AAAAA
AAAAABBBBBBBBBBBBBAAABBBBBBBBBBBBBBBBBBBBBBAAA5555555555555AAAAA
AAAAABBBBBBBBBBBBBAAABBBBBBBBBBBBBBBBBBBBBBAAA5555555555555AAAAA
AAAAABBBBBBBBBBBBBAAABBBBBBBBBBBBBBBBBBBBBBAAA5555555555555AAAAA
AAAAABBBBBBBBBBBBBAAABBBBBBBBBBBBBBBBBBBBBBAAA5555555555555AAAAA
AAAAABBBBBBBBBBBBBAAABBBBBBBBBBBBBBBBBBBBBBAAA5555555555555AAAAA
AAAAABBBBBBBBBBBBBAAABBBBBBBBBBBBBBBBBBBBBBAAA5555555555555AAAAA
AAAAABBBBBBBBBBBBBAAABBBBBBBBBBBBBBBBBBBBBBAAA5555555555555AAAAA
AAAAABBBBBBBBBBBBBBAAABBBBBBBBBBBBBBBBBBBBAAA55555555555555AAAAA
AAAAABBBBBBBBBBBBBBAAABBBBBBBBBBBBBBBBBBBBAAA55555555555555AAAAA
AAAAAABBBBBBBBBBBBBAAAABBBBBBBBBBBBBBBBBBAAAA55555555555559AAAAA
AAAAAABBBBBBBBBBBBBBAAABBBBBBBBBBBBBBBBBBAAA55555555555555AAAAAA
AAAAAABBBBBBBBBBBBBBBAAABBBBBBBBBBBBBBBBAAA555555555555555AAAAAA
AAAAAABBBBBBBBBBBBBBBAAAABBBBBBBBBBBBBBAAAA555555555555555AAAAAA
AAAAAAABBBBBBBBBBBBBBBAAAABBBBBBBBBBBBAAAA555555555555555AAAAAAA
AAAAAAABBBBBBBBBBBBBBBBBABBBBBBBBBBBBBBAAAA55555555555555AAAAAAA
AAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAA555555555555AAAAAAAA
AAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAA55555555555AAAAAAAA
AAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAA555555555AAAAAAAAA
AAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAA55555556AAAAAAAAA
AAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAA555555AAAAAAAAAA
AAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAA5555AAAAAAAAAAA
AAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAA55AAAAAAAAAAAA
AAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
}


!define SITECORE_CDP(alias) PUML_ENTITY(component,SITECORE_COLOR,cdp,alias,cdp)

!definelong SITECORE_CDP(alias,label,e_type="component",e_color="SITECORE_COLOR",e_stereo="Sitecore",e_sprite="cdp")
PUML_ENTITY(e_type,e_color,e_sprite,label,alias,e_stereo)
!enddefinelong


'connect.puml
sprite $connect [64x64/16] {
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA5555AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAA555555AAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAA5555555555AAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAA55555555555556AAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAA555555555555555556AAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAA55555555555555555555AAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAA555555555555555555555555AAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAA6555555555555555555555555556AAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAA955555555555555555555555555559AAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAABAAA555555555555555555555555555555AAAAAAAAAAAAAAA
AAAAAAAAAAAAABBBAAAA5555555555555555555555555555555AAAAAAAAAAAAA
AAAAAAAAAAAABBBBBAAA55555AAAAAA6555555555555555555555AAAAAAAAAAA
AAAAAAAAAABBBBBBBAAAA56AAAAAAAAAA555555555555555555555AAAAAAAAAA
AAAAAAAABBBBBBBBBBAAAAAAAAAAAAAAAA5555555555555555555555AAAAAAAA
AAAAAAABBBBBBBBBBBBAAAAAABBBBBBAAA5555555555555555555555AAAAAAAA
AAAAAAABBBBBBBBBBBBAAAABBBBBBBBBAAA555555555555555555555AAAAAAAA
AAAAAAABBBBBBBBBBBBBAABBBBBBBBBBAAA555555555555555555555AAAAAAAA
AAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBAAA555555555555555555555AAAAAAAA
AAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBAAA555555555555555555555AAAAAAAA
AAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBAAA555555555555555555555AAAAAAAA
AAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBAAA555555555555555555555AAAAAAAA
AAAAAAABBBBBBBBBBBBBBBBBBBBBBBBAAA5555555555555555555555AAAAAAAA
AAAAAAABBBBBBBBBBBBBBBBBBBBBBBAAAA5555555555555555555555AAAAAAAA
AAAAAAABBBBBBBBBBBBBBBBBBBBBAAAAA55555555555555555555555AAAAAAAA
AAAAAAABBBBBBBBBBBBBBBBBBBAAAAA5555555555555555555555555AAAAAAAA
AAAAAAABBBBBBBBBBBBBBBBBBAAAAA55555555555555555555555555AAAAAAAA
AAAAAAABBBBBBBBBBBBBBBBBBBAAA555555555555555555555555555AAAAAAAA
AAAAAAABBBBBBBBBBBBBBBBBBBAAA555555555555555555555555555AAAAAAAA
AAAAAAABBBBBBBBBBBBBBBBBBBBAAA55555555555555555555555555AAAAAAAA
AAAAAAABBBBBBBBBBBBBBBBBBBBAAAA55555AAAAA555555555555555AAAAAAAA
AAAAAAABBBBBBBBBBBBBBBBBBBBBAAA555AAAAAAAAA5555555555555AAAAAAAA
AAAAAAABBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAAAAAAA555555555555AAAAAAAA
AAAAAAABBBBBBBBBBBBBBBBBBBBBBAAAAAAAABBBAAAAA55555555555AAAAAAAA
AAAAAAABBBBBBBBBBBBBBBBBBBBBBBAAAAABBBBBBBAAA55555555555AAAAAAAA
AAAAAAABBBBBBBBBBBBBBBBBBBBBBBAAABBBBBBBBBAAAA5555555555AAAAAAAA
AAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAA5555555555AAAAAAAA
AAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAA5555555555AAAAAAAA
AAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAA5555555555AAAAAAAA
AAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAA5555555555AAAAAAAA
AAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAA55555555555AAAAAAAA
AAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAA55555555555AAAAAAAA
AAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAA555555555555AAAAAAAA
AAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAA5555555555555AAAAAAAA
AAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBAAAAA5555555555555AAAAAAAAAA
AAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBAAAA5555555555555AAAAAAAAAAA
AAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBAAA55555555555AAAAAAAAAAAAA
AAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBAAA655555555AAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBAAA5555559AAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBAAAA5555AAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBAAA55AAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
}


!define SITECORE_CONNECT(alias) PUML_ENTITY(component,SITECORE_COLOR,connect,alias,connect)

!definelong SITECORE_CONNECT(alias,label,e_type="component",e_color="SITECORE_COLOR",e_stereo="Sitecore",e_sprite="connect")
PUML_ENTITY(e_type,e_color,e_sprite,label,alias,e_stereo)
!enddefinelong


'contenthubone.puml
sprite $hubone [64x64/16] {
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAABBBBBBBBBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAABBBBBBBBBBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAABBBBBBBBBBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAABBBBBBBBBBAAA65555555555555555555555555AAAAAAAAAAAAA
AAAAAAAAAAAABBBBBBBBBAAAA5555555555555555555555555AAAAAAAAAAAAAA
AAAAAAAAAAABBBBBBBBBAAAA55555555555555555555555559AAAAAAAAAAAAAA
AAAAAAAAAABBBBBBBBBAAAA55555555555555555555555555AAAAAAAAAAAAAAA
AAAAAAAAABBBBBBBBBBAAA65555555555555555555555555AAAAAAAAAAAAAAAA
AAAAAAAABBBBBBBBBBAAA55555555555555555555555555AAAAAAAAAAAAAAAAA
AAAAAAAABBBBBBBBBAAAA5555555555555555555555555AAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
}


!define SITECORE_CONTENTHUBONE(alias) PUML_ENTITY(component,SITECORE_COLOR,contenthubone,alias,contenthubone)

!definelong SITECORE_CONTENTHUBONE(alias,label,e_type="component",e_color="SITECORE_COLOR",e_stereo="Sitecore",e_sprite="contenthubone")
PUML_ENTITY(e_type,e_color,e_sprite,label,alias,e_stereo)
!enddefinelong


'discover.puml
sprite $discover [64x64/16] {
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAAAAAAAAAA
AAAAA5555555555AAABBBBBBBBBBBBBBBBBBBBBBBBBBBBAAA5555555555AAAAA
AAAAA5555555555AAABBBBBBBBBBBBBBBBBBBBBBBBBBBBAAA5555555555AAAAA
AAAAA5555555555AAABBBBBBBBBBBBBBBBBBBBBBBBBBBBAAA5555555555AAAAA
AAAAA5555555555AAABBBBBBBBBBBBBBBBBBBBBBBBBBBBAAA5555555555AAAAA
AAAAA5555555555AAABBBBBBBBBBBBBBBBBBBBBBBBBBBBAAA5555555555AAAAA
AAAAA5555555555AAABBBBBBBBBBBBBBBBBBBBBBBBBBBBAAA5555555555AAAAA
AAAAA5555555555AAABBBBBBBBBBBBBBBBBBBBBBBBBBBBAAA5555555555AAAAA
AAAAA5555555555AAABBBBBBBBBBBBBBBBBBBBBBBBBBBBAAA5555555555AAAAA
AAAAA5555555555AAABBBBBBBBBBBBBBBBBBBBBBBBBBBBAAA5555555555AAAAA
AAAAA5555555555AAABBBBBBBBBBBBBBBBBBBBBBBBBBBBAAA5555555555AAAAA
AAAAA5555555555AAABBBBBBBBBBBBBBBBBBBBBBBBBBBBAAA5555555555AAAAA
AAAAA5555555555AAABBBBBBBBBBBBBBBBBBBBBBBBBBBBAAA5555555555AAAAA
AAAAA5555555555AAABBBBBBBBBBBBBBBBBBBBBBBBBBBBAAA5555555555AAAAA
AAAAA5555555555AAABBBBBBBBBBBBBBBBBBBBBBBBBBBBAAA5555555555AAAAA
AAAAA5555555555AAABBBBBBBBBBBBBBBBBBBBBBBBBBBBAAA5555555555AAAAA
AAAAA5555555555AAABBBBBBBBBBBBBBBBBBBBBBBBBBBBAAA5555555555AAAAA
AAAAA5555555555AAABBBBBBBBBBBBBBBBBBBBBBBBBBBBAAA5555555555AAAAA
AAAAA5555555555AAABBBBBBBBBBBBBBBBBBBBBBBBBBBBAAA5555555555AAAAA
AAAAA5555555555AAABBBBBBBBBBBBBBBBBBBBBBBBBBBBAAA5555555555AAAAA
AAAAA5555555555AAABBBBBBBBBBBBBBBBBBBBBBBBBBBBAAA5555555555AAAAA
AAAAA5555555555AAABBBBBBBBBBBBBBBBBBBBBBBBBBBBAAA5555555555AAAAA
AAAAA5555555555AAABBBBBBBBBBBBBBBBBBBBBBBBBBBBAAA5555555555AAAAA
AAAAA5555555555AAABBBBBBBBBBBBBBBBBBBBBBBBBBBBAAA5555555555AAAAA
AAAAA5555555555AAABBBBBBBBBBBBBBBBBBBBBBBBBBBBAAA5555555555AAAAA
AAAAA5555555555AAABBBBBBBBBBBBBBBBBBBBBBBBBBBBAAA5555555555AAAAA
AAAAA5555555555AAABBBBBBBBBBBBBBBBBBBBBBBBBBBBAAA5555555555AAAAA
AAAAA5555555555AAABBBBBBBBBBBBBBBBBBBBBBBBBBBBAAA5555555555AAAAA
AAAAA5555555555AAABBBBBBBBBBBBBBBBBBBBBBBBBBBBAAA5555555555AAAAA
AAAAA5555555555AAABBBBBBBBBBBBBBBBBBBBBBBBBBBBAAA5555555555AAAAA
AAAAA5555555555AAABBBBBBBBBBBBBBBBBBBBBBBBBBBBAAA5555555555AAAAA
AAAAA5555555555AAABBBBBBBBBBBBBBBBBBBBBBBBBBBBAAA5555555555AAAAA
AAAAA5555555555AAABBBBBBBBBBBBBBBBBBBBBBBBBBBBAAA5555555555AAAAA
AAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
}


!define SITECORE_DISCOVER(alias) PUML_ENTITY(component,SITECORE_COLOR,discover,alias,discover)

!definelong SITECORE_DISCOVER(alias,label,e_type="component",e_color="SITECORE_COLOR",e_stereo="Sitecore",e_sprite="discover")
PUML_ENTITY(e_type,e_color,e_sprite,label,alias,e_stereo)
!enddefinelong


'ordercloud.puml
sprite $ordercloud [64x64/16] {
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBAAAAAAAAAAAAAAAAAAAAAA
AAAAAABBBBAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBAAAAAAAAAAAA5555AAAAAA
AAAAAABBBBBAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBAAAAAAAAAAA55555AAAAAA
AAAAAABBBBBBBAAAAAAAAABBBBBBBBBBBBBBBBBBBBAAAAAAAAA5555555AAAAAA
AAAAAABBBBBBBBBAAAAAAABBBBBBBBBBBBBBBBBBBBAAAAAAA655555555AAAAAA
AAAAAABBBBBBBBBBBAAAAABBBBBBBBBBBBBBBBBBBBAAAAAA5555555555AAAAAA
AAAAAABBBBBBBBBBBBAAAABBBBBBBBBBBBBBBBBBAAAAAA555555555555AAAAAA
AAAAAABBBBBBBBBBBBBBAABBBBBBBBBBBBBBBBBAAAAA65555555555555AAAAAA
AAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAA6555555555555555AAAAAA
AAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAA55555555555555555AAAAAA
AAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAA5555555555555555555AAAAAA
AAAAAABBBBBBBBBBBBBBBBBBBBBBBBBAAAAAA555555555555555555555AAAAAA
AAAAAABBBBBBBBBBBBBBBBBBBBBBBBAAAAA55555555555555555555555AAAAAA
AAAAAABBBBBBBBBBBBBBBBBBBBBBAAAAAA555555555555555555555555AAAAAA
AAAAAABBBBBBBBBBBBBBBBBBBBBBAAAA55555555555555555555555555AAAAAA
AAAAAABBBBBBBBBBBBBBBBBBBBBBAAAA55555555555555555555555555AAAAAA
AAAAAABBBBBBBBBBBBBBBBBBBBBBAAAA55555555555555555555555555AAAAAA
AAAAAABBBBBBBBBBBBBBBBBBBBBBAAAA55555555555555555555555555AAAAAA
AAAAAABBBBBBBBBBBBBBBBBBBBBBAAAA55555555555555555555555555AAAAAA
AAAAAABBBBBBBBBBBBBBBBBBBBBBAAAA55555555555555555555555555AAAAAA
AAAAAABBBBBBBBBBBBBBBBBBBBBBAAAA55555555555555555555555555AAAAAA
AAAAAABBBBBBBBBBBBBBBBBBBBBBAAAA55555555555555555555555555AAAAAA
AAAAAABBBBBBBBBBBBBBBBBBBBBBAAAA55555555555555555555555555AAAAAA
AAAAAABBBBBBBBBBBBBBBBBBBBBBAAAA55555555555555555555555555AAAAAA
AAAAAABBBBBBBBBBBBBBBBBBBBBBAAAA55555555555555555555555555AAAAAA
AAAAAABBBBBBBBBBBBBBBBBBBBBBAAAA55555555555555555555555555AAAAAA
AAAAAABBBBBBBBBBBBBBBBBBBBBBAAAA55555555555555555555555555AAAAAA
AAAAAABBBBBBBBBBBBBBBBBBBBBBAAAA55555555555555555555555555AAAAAA
AAAAAABBBBBBBBBBBBBBBBBBBBBBAAAA55555555555555555555555556AAAAAA
AAAAAAABBBBBBBBBBBBBBBBBBBBBAAAA5555555555555555555555555AAAAAAA
AAAAAAAABBBBBBBBBBBBBBBBBBBBAAAA555555555555555555555555AAAAAAAA
AAAAAAAAAABBBBBBBBBBBBBBBBBBAAAA5555555555555555555555AAAAAAAAAA
AAAAAAAAAAAABBBBBBBBBBBBBBBBAAAA55555555555555555555AAAAAAAAAAAA
AAAAAAAAAAAAAABBBBBBBBBBBBBBAAAA5555555555555555559AAAAAAAAAAAAA
AAAAAAAAAAAAAAAABBBBBBBBBBBBAAAA55555555555555555AAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAABBBBBBBBBBBAAAA555555555555555AAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAABBBBBBBBBAAAA5555555555555AAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAABBBBBBBBAAAA555555555555AAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAABBBBBBAAAA5555555555AAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAABBBBAAAA55555555AAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAABBAAAA555555AAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAABAAAA55555AAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA555AAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA5AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
}


!define SITECORE_ORDERCLOUD(alias) PUML_ENTITY(component,SITECORE_COLOR,ordercloud,alias,ordercloud)

!definelong SITECORE_ORDERCLOUD(alias,label,e_type="component",e_color="SITECORE_COLOR",e_stereo="Sitecore",e_sprite="ordercloud")
PUML_ENTITY(e_type,e_color,e_sprite,label,alias,e_stereo)
!enddefinelong


'personalize.puml
sprite $personalize [64x64/16] {
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAA555555AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAA6555555555AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAA555555555555AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAA55555555555555AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAA555555555555555AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAA55555555555555555AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAA555555555555555555AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAA5555555555555555555AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAA55555555555555555555AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAA555555555555555555555AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAA5555555555555555555555AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAA95555555555555555555555AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAA55555555555555555555555AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAA65555555555555555555AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAA555555555555555556AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAA55555555555555555AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAA5555555555555556AAAAABBBBBBBBAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAA5555555555555555AAAABBBBBBBBBBBBAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAA555555555555555AAAABBBBBBBBBBBBBBBAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAA55555555555555AAAABBBBBBBBBBBBBBBBBAAAAAAAAAAAAAAAAAAAAAAA
AAAAAA55555555555555AAABBBBBBBBBBBBBBBBBBAAAAAAAAAAAAAAAAAAAAAAA
AAAAA55555555555555AAABBBBBBBBBBBBBBBBBBBBAAAAAAAAAAAAAAAAAAAAAA
AAAAA55555555555555AAABBBBBBBBBBBBBBBBBBBBAAAAAAAAAAAAAAAAAAAAAA
AAAAA5555555555555AAABBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAAAAAAAAAAAAA
AAAAA5555555555555AAABBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAAAAAAAAAAAAA
AAAAA5555555555555AAABBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAAAAAAAAAAAAA
AAAAA5555555555555AAABBBBBBBBBBBBBBBBBBBBBBAAAAABBBBBBBBBBAAAAAA
AAAAA5555555555555AAABBBBBBBBBBBBBBBBBBBBBBAAABBBBBBBBBBBBBAAAAA
AAAAA5555555555555AAABBBBBBBBBBBBBBBBBBBBBBAAABBBBBBBBBBBBBAAAAA
AAAAA5555555555555AAABBBBBBBBBBBBBBBBBBBBBBAAABBBBBBBBBBBBBAAAAA
AAAAA5555555555555AAABBBBBBBBBBBBBBBBBBBBBBAAABBBBBBBBBBBBBAAAAA
AAAAA5555555555555AAABBBBBBBBBBBBBBBBBBBBBAAABBBBBBBBBBBBBBAAAAA
AAAAA5555555555555AAABBBBBBBBBBBBBBBBBBBBBAAABBBBBBBBBBBBBBAAAAA
AAAAAA555555555555AAABBBBBBBBBBBBBBBBBBBBAAABBBBBBBBBBBBBBAAAAAA
AAAAAA555555555555AAABBBBBBBBBBBBBBBBBBBAAAABBBBBBBBBBBBBBAAAAAA
AAAAAA555555555555AAABBBBBBBBBBBBBBBBBBAAAABBBBBBBBBBBBBBBAAAAAA
AAAAAA955555555555AAABBBBBBBBBBBBBBBBBAAAABBBBBBBBBBBBBBBBAAAAAA
AAAAAAA55555555555AAABBBBBBBBBBBBBBBAAAAABBBBBBBBBBBBBBBBAAAAAAA
AAAAAAA55555555555AAABBBBBBBBBBBBAAAAAAABBBBBBBBBBBBBBBBBAAAAAAA
AAAAAAAA5555555555AAABBBBBBBBBBBAAAAAABBBBBBBBBBBBBBBBBBAAAAAAAA
AAAAAAAA6555555555AAABBBBBBBBBBBAAAABBBBBBBBBBBBBBBBBBBBAAAAAAAA
AAAAAAAAA555555555AAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAA
AAAAAAAAAA55555555AAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAA
AAAAAAAAAA65555555AAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAA
AAAAAAAAAAA5555555AAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAAA
AAAAAAAAAAAA555555AAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAAAA
AAAAAAAAAAAAA55555AAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAAAAA
AAAAAAAAAAAAAA5555AAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAAAAAA
AAAAAAAAAAAAAAA555AAABBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAA5AAABBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
}


!define SITECORE_PERSONALIZE(alias) PUML_ENTITY(component,SITECORE_COLOR,personalize,alias,personalize)

!definelong SITECORE_PERSONALIZE(alias,label,e_type="component",e_color="SITECORE_COLOR",e_stereo="Sitecore",e_sprite="personalize")
PUML_ENTITY(e_type,e_color,e_sprite,label,alias,e_stereo)
!enddefinelong


'search.puml
sprite $search [64x64/16] {
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAA
AAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAA
AAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAA
AAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAA
AAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAA
AAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAA
AAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAA
AAAAAAAAAAAAAAAABBBBBBBBBBBBBAAAAAAAABBBBBBBBBBBBBBBBBBBBBAAAAAA
AAAAAAAAAAAAAABBBBBBBBBBBBAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBAAAAAA
AAAAAAAAAAAAABBBBBBBBBBBBAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBAAAAAA
AAAAAAAAAAAABBBBBBBBBBBAAAAAA55555556AAAAABBBBBBBBBBBBBBBBAAAAAA
AAAAAAAAAAABBBBBBBBBBBAAAAA555555555555AAAABBBBBBBBBBBBBBBAAAAAA
AAAAAAAAAABBBBBBBBBBBBAAA555555555555555AAAABBBBBBBBBBBBBAAAAAAA
AAAAAAAABBBBBBBBBBBBBAAA55555555555555555AAABBBBBBBBBBBBBAAAAAAA
AAAAAAABBBBBBBBBBBBBAAA5555555555555555555AAABBBBBBBBBBBBAAAAAAA
AAAAAAABBBBBBBBBBBBBAAA55555555555555555559AAABBBBBBBBBBBAAAAAAA
AAAAAAABBBBBBBBBBBBAAA555555555555555555555AAABBBBBBBBBBBAAAAAAA
AAAAAAAAAAABBBBBBBBAAA555555555555555555555AAABBBBBBBBBBBAAAAAAA
AAAAAAAAAAAAAAAAABBAAA5555555555555555555556AAABBBBBBBBBBAAAAAAA
AAAAAAAAAAAAAAAAAAAAAA5555555555555555555555AAABBBBBBBBBBAAAAAAA
AAAAAAAAAAAAAAAAAAAAAA5555555555555555555555AAABBBBBBBBBBAAAAAAA
AAAAAAAAAAAAAAAAAAAAAA5555555555555555555555AAABBBBBBBBBBAAAAAAA
AAAAAAAAAAAAAAAAAAAAAA5555555555555555555555AAABBBBBBBBBBAAAAAAA
AAAAAAAAAAAAAAAAAAAAAA5555555555555555555556AAABBBBBBBBBBAAAAAAA
AAAAAAAAAAAAAAAAAAAAAA555555555555555555555AAABBBBBBBBBBAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAA555555555555555555555AAABBBBBBBBBBAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAA55555555555555555559AAABBBBBBBBBBAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAA5555555555555555555AAABBBBBBBBBBBAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAA55555555555555555AAABBBBBBBBBBBBAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAA655555555555555AAAABBBBBBBBBBBBAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAA555555555556AAAABBBBBBBBBBBBAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAA55555556AAAAABBBBBBBBBBBBAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
}


!define SITECORE_SEARCH(alias) PUML_ENTITY(component,SITECORE_COLOR,search,alias,search)

!definelong SITECORE_SEARCH(alias,label,e_type="component",e_color="SITECORE_COLOR",e_stereo="Sitecore",e_sprite="search")
PUML_ENTITY(e_type,e_color,e_sprite,label,alias,e_stereo)
!enddefinelong


'send.puml
sprite $send [64x64/16] {
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA5AAAABAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA55AAABBAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA555AAAABBAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA555AAAABBBAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA5555AAAABBBBAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA55559AAABBBBBAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA955555AAABBBBBBAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA555555AAABBBBBBBAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA555555AAAABBBBBBBAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA6555555AAAABBBBBBBBAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA5555555AAAABBBBBBBBBAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA65555555AAAABBBBBBBBBBAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA555555556AAABBBBBBBBBBBAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA555555555AAABBBBBBBBBBBBAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAA6555555555AAAABBBBBBBBBBBBAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAA5555555555AAAABBBBBBBBBBBBBAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAA55555555555AAAABBBBBBBBBBBBBBAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAA55555555555AAAABBBBBBBBBBBBBBBAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAA555555555555AAABBBBBBBBBBBBBBBBAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAA5555555555556AAABBBBBBBBBBBBBBBBBAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAA5555555555555AAAABBBBBBBBBBBBBBBBBAAAAAAAAAA
AAAAAAAAAAAAAAAAAA55555555555555AAAABBBBBBBBBBBBBBBBBBAAAAAAAAAA
AAAAAAAAAAAAAAAAA55555555555555AAAABBBBBBBBBBBBBBBBBBBAAAAAAAAAA
AAAAAAAAAAAAAAA955555555555555AAAABBBBBBBBBBBBBBBBBBBBAAAAAAAAAA
AAAAAAAAAAAAAA5555555555555556AAABBBBBBBBBBBBBBBBBBBBBAAAAAAAAAA
AAAAAAAAAAAAA5555555555555556AAAABBBBBBBBBBBBBBBBBBBBBAAAAAAAAAA
AAAAAAAAAAA55555555555555555AAAABBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAA
AAAAAAAAAA55555555555555555AAAABBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAA
AAAAAAAA655555555555555555AAAABBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAA
AAAAAAA555555555555555555AAAABBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAA
AAAAAAA555555555555555555AAABBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAA
AAAAAAAAA555555555555555AAAABBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAA
AAAAAAAAAAA555555555555AAAABBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAA
AAAAAAAAAAAAAA55555555AAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAA
AAAAAAAAAAAAAAAAA5555AAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAA
AAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAA
AAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBAAAAAABBBBBBBBBBBBBBBAAAAAAAAAA
AAAAAAAAAAAAAAAAABBBBBBBBBBBAAAAAAAAAAAAABBBBBBBBBBBBBAAAAAAAAAA
AAAAAAAAAAAAAAAABBBBBBBBBAAAAAAAAAAAAAAAAAAABBBBBBBBBBAAAAAAAAAA
AAAAAAAAAAAAAAAABBBBBAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
}


!define SITECORE_SEND(alias) PUML_ENTITY(component,SITECORE_COLOR,send,alias,send)

!definelong SITECORE_SEND(alias,label,e_type="component",e_color="SITECORE_COLOR",e_stereo="Sitecore",e_sprite="send")
PUML_ENTITY(e_type,e_color,e_sprite,label,alias,e_stereo)
!enddefinelong


'sitecore.puml
sprite $sitecore [64x64/16] {
AAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAAAAAA
AAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAAAAA
AAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAAAA
AAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAA
AAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAA
AAAAAAAAABBBBBBBBBBBBBBBBBBBAAAAAAAABBBBBBBBBBBBBBBBBBBAAAAAAAAA
AAAAAAABBBBBBBBBBBBBBBBBBAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBAAAAAAA
AAAAAAABBBBBBBBBBBBBBBAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBAAAAAAA
AAAAAABBBBBBBBBBBBBBAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBAAAAAA
AAAAABBBBBBBBBBBBBBAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBAAAAA
AAAABBBBBBBBBBBBBBAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBAAAA
AAAABBBBBBBBBBBBBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBAAAA
AAABBBBBBBBBBBBBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBAAA
AAABBBBBBBBBBBBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBAAA
AABBBBBBBBBBBBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBAA
AABBBBBBBBBBBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBAA
AABBBBBBBBBBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBABBBBBBBBBBAA
ABBBBBBBBBBBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBA
ABBBBBBBBBBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBABBBBBBBBBBA
ABBBBBBBBBBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBA
BBBBBBBBBBBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBABBBBBBBBB
BBBBBBBBBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBABBBBBBBBB
BBBBBBBBBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBB
BBBBBBBBBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBB
BBBBBBBBBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBABBBBBBBBB
BBBBBBBBBBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBABBBBBBBBBBBBBBBBBB
BBBBBBBBBBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBB
ABBBBBBBBBBAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBA
ABBBBBBBBBBABAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBABBBBBBBBBBA
ABBBBBBBBBBBBBAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBA
AABBBBBBBBBBBBBAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBAA
AABBBBBBBBBBBBBBAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBAA
AABBBBBBBBBBBBBBBAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAA
AAABBBBBBBBBBBBBBBABBAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAA
AAABBBBBBBBBBBBABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAA
AAAABBBBBBBBBBBBABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAA
AAAABBBBBBBBBBBBBABBBBBBBBBBBBBBBBBABBBBBBBBBBBBBBBBBBBBBBBBAAAA
AAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAA
AAAAAABBBBBBBBBBBBBBABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAA
AAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAA
AAAAAAABBBBBBBBBBBBBBBBBABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAA
AAAAAAAAABBBBBBBBBBBBBBBBBBBBAABBBABBBBBBBBBBBBBBBBBBBBAAAAAAAAA
AAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAA
AAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAA
AAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAAAA
AAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAAAAA
AAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBAAAAAAAAAAAAAAAAAAAAAAAA
}


!define SITECORE_SITECORE(alias) PUML_ENTITY(component,SITECORE_COLOR,sitecore,alias,sitecore)

!definelong SITECORE_SITECORE(alias,label,e_type="component",e_color="SITECORE_COLOR",e_stereo="Sitecore",e_sprite="sitecore")
PUML_ENTITY(e_type,e_color,e_sprite,label,alias,e_stereo)
!enddefinelong


'xc.puml
sprite $xc [64x64/16] {
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBAAAAAAAAAAAAAA
AA5555555555555AAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBAAAAAAAAAAA
AAA5555555555555AAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBAAAAAAAAA
AAA95555555555555AAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAA
AAAA55555555555555AAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAA
AAAAA5555555555555AAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAA
AAAAAA5555555555555AAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAA
AAAAAAA5555555555555AAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAA
AAAAAAA55555555555555AAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAA
AAAAAAAA5555555555555AAAAABBBBBBBBBBBBBBBAAAAAAABBBBBBBBAAAAAAAA
AAAAAAAAA5555555555555AAAABBBBBBBBBBBBBBAAAAAAAAAABBBBBAAAAAAAAA
AAAAAAAAAA5555555555555AAABBBBBBBBBBBBAAAAAAAAAAAAABBBAAAAAAAAAA
AAAAAAAAAA55555555555556ABBBBBBBBBBBBAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAA5555555555555AABBBBBBBBBBBAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAA5555555555555AABBBBBBBBBAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAA5555555555555ABBBBBBBBBAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAA65555555555555ABBBBBBBAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAA5555555555555AABBBBBBAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAA5555555555555AABBBBBAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAA5555555555555ABBBBBAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAA5555555555555ABBBBBAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAA5555555555555ABBBBBBAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAA5555555555555ABBBBBBBAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAA55555555555556ABBBBBBBAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAA5555555555555ABBBBBBBBBAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAA5555555555555ABBBBBBBBBBAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAA5555555555555AABBBBBBBBBBBAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAA65555555555555ABBBBBBBBBBBBBAAAAAAAAAAAAAABBAAAAAAAAAA
AAAAAAAAAA5555555555555AAABBBBBBBBBBBBBAAAAAAAAAAAABBBBAAAAAAAAA
AAAAAAAAA5555555555555AAAABBBBBBBBBBBBBBAAAAAAAAABBBBBBBAAAAAAAA
AAAAAAAA5555555555555AAAAAABBBBBBBBBBBBBBBAAAAABBBBBBBBBBAAAAAAA
AAAAAAA55555555555555AAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAA
AAAAAA95555555555555AAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAA
AAAAAA5555555555555AAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAA
AAAAA5555555555555AAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAA
AAAA65555555555556AAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAA
AAA95555555555555AAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBAAAAAAAA
AAA5555555555555AAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBAAAAAAAAAA
AA3555555555555AAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
}


!define SITECORE_XC(alias) PUML_ENTITY(component,SITECORE_COLOR,xc,alias,xc)

!definelong SITECORE_XC(alias,label,e_type="component",e_color="SITECORE_COLOR",e_stereo="Sitecore",e_sprite="xc")
PUML_ENTITY(e_type,e_color,e_sprite,label,alias,e_stereo)
!enddefinelong


'xm.puml
sprite $xm [64x64/16] {
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
5555555555557AAAAAAAABBBBBBBBBBBBBBAAAAAAAAAAAAAAAABBBBBBBBBBBBB
5555555555555AAAAAAAABBBBBBBBBBBBBBAAAAAAAAAAAAAAABBBBBBBBBBBBBB
A5555555555555AAAAAAABBBBBBBBBBBBBBBAAAAAAAAAAAAAABBBBBBBBBBBBBB
AA5555555555555AAAAAABBBBBBBBBBBBBBBAAAAAAAAAAAAABBBBBBBBBBBBBBB
AA55555555555556AAAAABBBBBBBBBBBBBBBAAAAAAAAAAAAABBBBBBBBBBBBBBB
AAA5555555555555AAAAABBBBBBBBBBBBBBBBAAAAAAAAAAAABBBBBBBBBBBBBBB
AAAA5555555555555AAAABBBBBBBBBBBBBBBBAAAAAAAAAAABBBBBBBBBBBBBBBB
AAAA95555555555555AAABBBBBBBBBBBBBBBBBAAAAAAAAAABBBBBBBBBBBBBBBB
AAAAA65555555555559AABBBBBBBBBBBBBBBBBAAAAAAAAAABBBBBBBBBBBBBBBB
AAAAAA5555555555555AABBBBBBBBBBBBBBBBBAAAAAAAAABBBBBBBBBBBBBBBBB
AAAAAAA5555555555555AABBBBBBBBBBBBBBBBBAAAAAAAABBBBBBBBBBBBBBBBB
AAAAAAA95555555555555ABBBBBBBBBBBBBBBBBAAAAAAAABBBBBBBBBBBBBBBBB
AAAAAAAA5555555555555AABBBBBBBBBBBBBBBBAAAAAAABBBBBBBBBBBBBBBBBB
AAAAAAAAA5555555555555AABBBBBBBBBBBBBBBBAAAAAABBBBBBBBBBBBBBBBBB
AAAAAAAAAA5555555555555ABBBBBBABBBBBBBBBAAAAAABBBBBBBBBBBBBBBBBB
AAAAAAAAAA55555555555556ABBBBBABBBBBBBBBAAAAABBBBBBBBBABBBBBBBBB
AAAAAAAAAAA5555555555555AABBBBABBBBBBBBBBAAAABBBBBBBBBABBBBBBBBB
AAAAAAAAAAAA5555555555555ABBBBAABBBBBBBBBAAAABBBBBBBBAABBBBBBBBB
AAAAAAAAAAAAA5555555555555ABBBAABBBBBBBBBAAABBBBBBBBBAABBBBBBBBB
AAAAAAAAAAAAA5555555555555ABBBAABBBBBBBBBBAABBBBBBBBBAABBBBBBBBB
AAAAAAAAAAAA5555555555555AABBBAAABBBBBBBBBAABBBBBBBBAAABBBBBBBBB
AAAAAAAAAAA55555555555556ABBBBAAABBBBBBBBBABBBBBBBBBAAABBBBBBBBB
AAAAAAAAAAA5555555555555ABBBBBAAABBBBBBBBBBBBBBBBBBBAAABBBBBBBBB
AAAAAAAAAA5555555555555ABBBBBBAAAABBBBBBBBBBBBBBBBBAAAABBBBBBBBB
AAAAAAAAA5555555555555AABBBBBBAAAABBBBBBBBBBBBBBBBBAAAABBBBBBBBB
AAAAAAAA55555555555555ABBBBBBBAAAABBBBBBBBBBBBBBBBBAAAABBBBBBBBB
AAAAAAAA5555555555555ABBBBBBBBAAAAABBBBBBBBBBBBBBBAAAAABBBBBBBBB
AAAAAAA5555555555555AABBBBBBBBAAAAABBBBBBBBBBBBBBBAAAAABBBBBBBBB
AAAAAA5555555555555AABBBBBBBBBAAAAABBBBBBBBBBBBBBAAAAAABBBBBBBBB
AAAAA55555555555555AABBBBBBBBBAAAAAABBBBBBBBBBBBBAAAAAABBBBBBBBB
AAAAA5555555555555AAABBBBBBBBBAAAAAABBBBBBBBBBBBBAAAAAABBBBBBBBB
AAAA5555555555555AAAABBBBBBBBBBAAAAABBBBBBBBBBBBAAAAAAABBBBBBBBB
AAA5555555555555AAAAABBBBBBBBBBAAAAAABBBBBBBBBBBAAAAAAABBBBBBBBB
AA55555555555556AAAAABBBBBBBBBAAAAAAABBBBBBBBBBBAAAAAAABBBBBBBBB
AA5555555555555AAAAAABBBBBBBBBBAAAAAAABBBBBBBBBAAAAAAAABBBBBBBBB
A5555555555555AAAAAAABBBBBBBBBBAAAAAAABBBBBBBBBAAAAAAAABBBBBBBBB
5555555555555AAAAAAAABBBBBBBBBBAAAAAAABBBBBBBBBAAAAAAAABBBBBBBBB
5555555555557AAAAAAAABBBBBBBBBBAAAAAAAABBBBBBBAAAAAAAAABBBBBBBBB
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
}


!define SITECORE_XM(alias) PUML_ENTITY(component,SITECORE_COLOR,xm,alias,xm)

!definelong SITECORE_XM(alias,label,e_type="component",e_color="SITECORE_COLOR",e_stereo="Sitecore",e_sprite="xm")
PUML_ENTITY(e_type,e_color,e_sprite,label,alias,e_stereo)
!enddefinelong


'xmcloud.puml
sprite $xmcloud [64x64/16] {
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAA6556AAAAAAAAAAAAAAAAAAAAAAAAAAAA6556AAAAAAAAAAAAAA
AAAAAAAAAAAAA655556AAAAAAAAAAAAAAAAAAAAAAAAAA555555AAAAAAAAAAAAA
AAAAAAAAAAAA65555555AAAAAAAAAAAAAAAAAAAAAAAA55555556AAAAAAAAAAAA
AAAAAAAAAAA65555555559AAAAAAAAAAAAAAAAAAAA55555555556AAAAAAAAAAA
AAAAAAAAAA6555555555555AAAAAAAAAAAAAAAAAA5555555555556AAAAAAAAAA
AAAAAAAAA65555555555555555AAAAAAAAAAAA55555555555555556AAAAAAAAA
AAAAAAAA655555555555555555555569565555555555555555555556AAAAAAAA
AAAAAAA65555555555555555555555555555555555555555555555555AAAAAAA
AAAAAAA55555555555555555555555555555555555555555555555555AAAAAAA
AAAAAAA55555555555555555555555555555555555555555555555555AAAAAAA
AAAAAAA55555555555555555555555555555555555555555555555555AAAAAAA
AAAAAAAA555555555555555555555555555555555555555555555555AAAAAAAA
AAAAAAAAA5555555555555555555555555555555555555555555555AAAAAAAAA
AAAAAAAAAA55555555555555555555555555555555555555555555AAAAAAAAAA
AAAAAAAAAAA555555555555555556AAAAAA655555555555555555AAAAAAAAAAA
AAAAAAAAAAAA55555555555555AAAAAAAAAAAA55555555555555AAAAAAAAAAAA
AAAAAAAAAAAAA55555555555AAAAAAAAAAAAAAAA55555555555AAAAAAAAAAAAA
AAAAAAAAAAAAAA555555555AAAAAABBBBBBAAAAAA555555555AAAAAAAAAAAAAA
AAAAAAAAAAAAAAA5555555AAAAABBBBBBBBBBBAAAA5555555AAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAA55555AAAABBBBBBBBBBBBBBAAAA55555AAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAA555AAAABBBBBBBBBBBBBBBBAAAA555AAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAA6AAAABBBBBBBBBBBBBBBBBBAAAA6AAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAAAAAAA
AAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAAAAAA
AAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAAAAA
AAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAAAA
AAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAAA
AAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAA
AAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAA
AAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAA
AAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAA
AAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAA
AAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAA
AAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAA
AAAAAAAABBBBBBBBBBBBBBBBBBBBBBBABBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAA
AAAAAAAAABBBBBBBBBBBBBBBBBAAAAAAAAAAAABBBBBBBBBBBBBBBBBAAAAAAAAA
AAAAAAAAAABBBBBBBBBBBBBAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBAAAAAAAAAA
AAAAAAAAAAABBBBBBBBBBBAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBAAAAAAAAAAA
AAAAAAAAAAAABBBBBBBBAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBAAAAAAAAAAAA
AAAAAAAAAAAAABBBBBBAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBAAAAAAAAAAAAA
AAAAAAAAAAAAAABBBBAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
}


!define SITECORE_XMCLOUD(alias) PUML_ENTITY(component,SITECORE_COLOR,xmcloud,alias,xmcloud)

!definelong SITECORE_XMCLOUD(alias,label,e_type="component",e_color="SITECORE_COLOR",e_stereo="Sitecore",e_sprite="xmcloud")
PUML_ENTITY(e_type,e_color,e_sprite,label,alias,e_stereo)
!enddefinelong


'xp.puml
sprite $xp [64x64/16] {
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAA5555555555556AAAAAAAAABBBBBBBBBBBBBBBBBBBBAAAAAAAAAAAAAA
AAAAAAAA55555555555556AAAAAAAABBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAAA
AAAAAAAAA5555555555555AAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAA
AAAAAAAAAA5555555555555AAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAA
AAAAAAAAAA65555555555555AAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAA
AAAAAAAAAAA55555555555555AAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAA
AAAAAAAAAAAA5555555555555AAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAA
AAAAAAAAAAAAA5555555555555AAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAA
AAAAAAAAAAAAA55555555555555AAABBBBBBBBBBAAAAAABBBBBBBBBBBBBAAAAA
AAAAAAAAAAAAAA55555555555555AABBBBBBBBBBAAAAAAAABBBBBBBBBBBAAAAA
AAAAAAAAAAAAAAA5555555555555AABBBBBBBBBBAAAAAAAAABBBBBBBBBBAAAAA
AAAAAAAAAAAAAAAA5555555555555ABBBBBBBBBBAAAAAAAAABBBBBBBBBBAAAAA
AAAAAAAAAAAAAAAA55555555555555ABBBBBBBBBAAAAAAAAABBBBBBBBBBAAAAA
AAAAAAAAAAAAAAAAA55555555555555ABBBBBBBBAAAAAAAAABBBBBBBBBBAAAAA
AAAAAAAAAAAAAAAAAA5555555555555AABBBBBBBAAAAAAAABBBBBBBBBBBAAAAA
AAAAAAAAAAAAAAAAAAA5555555555555ABBBBBBBAAAAAABBBBBBBBBBBBAAAAAA
AAAAAAAAAAAAAAAAAAA95555555555555ABBBBBBBBBBBBBBBBBBBBBBBBAAAAAA
AAAAAAAAAAAAAAAAAAAA65555555555556ABBBBBBBBBBBBBBBBBBBBBBBAAAAAA
AAAAAAAAAAAAAAAAAAAAA5555555555555AABBBBBBBBBBBBBBBBBBBBBAAAAAAA
AAAAAAAAAAAAAAAAAAAAA5555555555555AABBBBBBBBBBBBBBBBBBBBAAAAAAAA
AAAAAAAAAAAAAAAAAAAA65555555555556ABBBBBBBBBBBBBBBBBBBBAAAAAAAAA
AAAAAAAAAAAAAAAAAAA95555555555555ABBBBBBBBBBBBBBBBBBBBAAAAAAAAAA
AAAAAAAAAAAAAAAAAAA5555555555555ABBBBBBBBBBBBBBBBBBBAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAA5555555555555AABBBBBBBBBBBBBBBBAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAA55555555555555ABBBBBBBBAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAA55555555555555ABBBBBBBBBAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAA5555555555555ABBBBBBBBBBAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAA5555555555555AABBBBBBBBBBAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAA55555555555555AABBBBBBBBBBAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAA55555555555555AAABBBBBBBBBBAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAA5555555555555AAAABBBBBBBBBBAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAA5555555555555AAAAABBBBBBBBBBAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAA55555555555555AAAAABBBBBBBBBBAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAA65555555555555AAAAAABBBBBBBBBBAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAA5555555555555AAAAAAABBBBBBBBBBAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAA5555555555555AAAAAAAABBBBBBBBBBAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAA55555555555556AAAAAAAABBBBBBBBBBAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAA5555555555556AAAAAAAAABBBBBBBBBBAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
}


!define SITECORE_XP(alias) PUML_ENTITY(component,SITECORE_COLOR,xp,alias,xp)

!definelong SITECORE_XP(alias,label,e_type="component",e_color="SITECORE_COLOR",e_stereo="Sitecore",e_sprite="xp")
PUML_ENTITY(e_type,e_color,e_sprite,label,alias,e_stereo)
!enddefinelong

