sprite $sitecorecdp [76x64/8] {
________zjjjjz________________________________________________wIIIIw________
______zjjjjjjjjz____________________________________________wIIIIIIIIw______
_____zjjjjjjjjjjjz________________________________________wIIIIIIIIIIIw_____
____zjjjjjjjjjjjjjjz____________________________________wIIIIIIIIIIIIIIw____
___jjjjjjjjjjjjjjjjjjz________________________________wIIIIIIIIIIIIIIIIII___
__zjjjjjjjjjjjjjjjjjjjj________zzzjjjjjjjjzzz________IIIIIIIIIIIIIIIIIIIIw__
_zjjjjjjjjjjjjjjjjjjjjl_____zjjjjjjjjjjjjjjjjjjz_____NIIIIIIIIIIIIIIIIIIIIw_
_jjjjjjjjjjjjjjjjjjjj_____zjjjjjjjjjjjjjjjjjjjjjjz_____IIIIIIIIIIIIIIIIIIII_
jjjjjjjjjjjjjjjjjjjj_____jjjjjjjjjjjjjjjjjjjjjjjjjj_____IIIIIIIIIIIIIIIIIIII
jjjjjjjjjjjjjjjjjjj____yjjjjjjjjjjjjjjjjjjjjjjjjjjjjz____IIIIIIIIIIIIIIIIIII
jjjjjjjjjjjjjjjjjjl____jjjjjjjjjjjjjjjjjjjjjjjjjjjjjj____NIIIIIIIIIIIIIIIIII
jjjjjjjjjjjjjjjjjj____jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj____IIIIIIIIIIIIIIIIII
jjjjjjjjjjjjjjjjjj____jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj____IIIIIIIIIIIIIIIIII
jjjjjjjjjjjjjjjjjj____jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj____IIIIIIIIIIIIIIIIII
jjjjjjjjjjjjjjjjjj____ljjjjjjjjjjjjjjjjjjjjjjjjjjjjjjl____IIIIIIIIIIIIIIIIII
jjjjjjjjjjjjjjjjjjz____jjjjjjjjjjjjjjjjjjjjjjjjjjjjjj____wIIIIIIIIIIIIIIIIII
jjjjjjjjjjjjjjjjjjj_____jjjjjjjjjjjjjjjjjjjjjjjjjjjj_____IIIIIIIIIIIIIIIIIII
ljjjjjjjjjjjjjjjjjjj_____jjjjjjjjjjjjjjjjjjjjjjjjjj_____IIIIIIIIIIIIIIIIIIIN
_jjjjjjjjjjjjjjjjjjjj_____ljjjjjjjjjjjjjjjjjjjjjjl_____IIIIIIIIIIIIIIIIIIII_
_ljjjjjjjjjjjjjjjjjjjjz_____lljjjjjjjjjjjjjjjjll_____wIIIIIIIIIIIIIIIIIIIIN_
__ljjjjjjjjjjjjjjjjjjjjjz____zjjjjjjjjjjjjjjjjz______IIIIIIIIIIIIIIIIIIIIN__
___ljjjjjjjjjjjjjjjjjjjjjjzzjjjjjjjjjjjjjjjjjjjjz_____NIIIIIIIIIIIIIIIIIN___
____ljjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjz_____NIIIIIIIIIIIIIIN____
_____ljjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjz_____NIIIIIIIIIIIN_____
_______jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjz_____NIIIIIIII_______
________ljjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjz_____NIIIIN________
__________ljjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjz_________________
____________ljjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj________________
______________lljjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj________________
_________________lljjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjll_________________
_____________________lljjjjjjjjjjjjjjjjjjjjjjjjjjjjjjll_____________________
_________________________llljjjjjjjjjjjjjjjjjjjllll_________________________
}

