sprite $cdp [64x64/16] {
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAABBBBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA6555AAAAAAAAAAA
AAAAAAAAAAABBBBBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA55555AAAAAAAAAAA
AAAAAAAAAABBBBBBBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA6555555AAAAAAAAAA
AAAAAAAAABBBBBBBBBAAAAAAAAAAAAAAAAAAAAAAAAAAAA555555555AAAAAAAAA
AAAAAAAABBBBBBBBBBBAAAAAAAAAAAAAAAAAAAAAAAAAA65555555559AAAAAAAA
AAAAAAAABBBBBBBBBBBBAAAAAAAAAAAAAAAAAAAAAAAA555555555555AAAAAAAA
AAAAAAABBBBBBBBBBBBBBAAAAAAAAAAAAAAAAAAAAAA65555555555555AAAAAAA
AAAAAAABBBBBBBBBBBBBBAAAAAAAABBBBBBAAAAAAAA55555555555555AAAAAAA
AAAAAAABBBBBBBBBBBBBBAAAAABBBBBBBBBBBBAAAAA55555555555555AAAAAAA
AAAAAABBBBBBBBBBBBBBBAAAABBBBBBBBBBBBBBAAAA555555555555555AAAAAA
AAAAAABBBBBBBBBBBBBBAAAABBBBBBBBBBBBBBBBAAAA55555555555555AAAAAA
AAAAAABBBBBBBBBBBBBBAAABBBBBBBBBBBBBBBBBBAAA55555555555555AAAAAA
AAAAABBBBBBBBBBBBBBAAAABBBBBBBBBBBBBBBBBBBAAA55555555555555AAAAA
AAAAABBBBBBBBBBBBBBAAABBBBBBBBBBBBBBBBBBBBAAA55555555555555AAAAA
AAAAABBBBBBBBBBBBBBAABBBBBBBBBBBBBBBBBBBBBBAAA5555555555555AAAAA
AAAAABBBBBBBBBBBBBAAABBBBBBBBBBBBBBBBBBBBBBAAA5555555555555AAAAA
AAAAABBBBBBBBBBBBBAAABBBBBBBBBBBBBBBBBBBBBBAAA5555555555555AAAAA
AAAAABBBBBBBBBBBBBAAABBBBBBBBBBBBBBBBBBBBBBAAA5555555555555AAAAA
AAAAABBBBBBBBBBBBBAAABBBBBBBBBBBBBBBBBBBBBBAAA5555555555555AAAAA
AAAAABBBBBBBBBBBBBAAABBBBBBBBBBBBBBBBBBBBBBAAA5555555555555AAAAA
AAAAABBBBBBBBBBBBBAAABBBBBBBBBBBBBBBBBBBBBBAAA5555555555555AAAAA
AAAAABBBBBBBBBBBBBAAABBBBBBBBBBBBBBBBBBBBBBAAA5555555555555AAAAA
AAAAABBBBBBBBBBBBBBAAABBBBBBBBBBBBBBBBBBBBAAA55555555555555AAAAA
AAAAABBBBBBBBBBBBBBAAABBBBBBBBBBBBBBBBBBBBAAA55555555555555AAAAA
AAAAAABBBBBBBBBBBBBAAAABBBBBBBBBBBBBBBBBBAAAA55555555555559AAAAA
AAAAAABBBBBBBBBBBBBBAAABBBBBBBBBBBBBBBBBBAAA55555555555555AAAAAA
AAAAAABBBBBBBBBBBBBBBAAABBBBBBBBBBBBBBBBAAA555555555555555AAAAAA
AAAAAABBBBBBBBBBBBBBBAAAABBBBBBBBBBBBBBAAAA555555555555555AAAAAA
AAAAAAABBBBBBBBBBBBBBBAAAABBBBBBBBBBBBAAAA555555555555555AAAAAAA
AAAAAAABBBBBBBBBBBBBBBBBABBBBBBBBBBBBBBAAAA55555555555555AAAAAAA
AAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAA555555555555AAAAAAAA
AAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAA55555555555AAAAAAAA
AAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAA555555555AAAAAAAAA
AAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAA55555556AAAAAAAAA
AAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAA555555AAAAAAAAAA
AAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAA5555AAAAAAAAAAA
AAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAA55AAAAAAAAAAAA
AAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
}


!define SITECORE_CDP(alias) PUML_ENTITY(component,#EB001A,cdp,alias,cdp)

!definelong SITECORE_CDP(alias,label,e_type="component",e_color="#EB001A",e_stereo="Sitecore",e_sprite="cdp")
PUML_ENTITY(e_type,e_color,e_sprite,label,alias,e_stereo)
!enddefinelong
