sprite $sitecoreconnect [56x64/8] {
________________________wIIIIIIw________________________
____________________wwIIIIIIIIIIIIww____________________
_________________wwIIIIIIIIIIIIIIIIIIIw_________________
_____________wwIIIIIIIIIIIIIIIIIIIIIIIIIIww_____________
____________IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIww__________
______zzjz___NIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIww______
___zzjjjjjz___NIIINN_______NIIIIIIIIIIIIIIIIIIIIIIIww___
zjjjjjjjjjjz_________zzzz_____IIIIIIIIIIIIIIIIIIIIIIIIIw
jjjjjjjjjjjjj_____zjjjjjjjjz___IIIIIIIIIIIIIIIIIIIIIIIII
jjjjjjjjjjjjjjzzjjjjjjjjjjjj____IIIIIIIIIIIIIIIIIIIIIIII
jjjjjjjjjjjjjjjjjjjjjjjjjjjj____IIIIIIIIIIIIIIIIIIIIIIII
jjjjjjjjjjjjjjjjjjjjjjjjjjjl___wIIIIIIIIIIIIIIIIIIIIIIII
jjjjjjjjjjjjjjjjjjjjjjjjjll___wIIIIIIIIIIIIIIIIIIIIIIIII
jjjjjjjjjjjjjjjjjjjjjjl_____wIIIIIIIIIIIIIIIIIIIIIIIIIII
jjjjjjjjjjjjjjjjjjjj_____wwIIIIIIIIIIIIIIIIIIIIIIIIIIIII
jjjjjjjjjjjjjjjjjjjjj____IIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
jjjjjjjjjjjjjjjjjjjjjj____IIIIIIIINNNIIIIIIIIIIIIIIIIIII
jjjjjjjjjjjjjjjjjjjjjjjz___IIIN_________NIIIIIIIIIIIIIII
jjjjjjjjjjjjjjjjjjjjjjjjz________zzzzz____NIIIIIIIIIIIII
jjjjjjjjjjjjjjjjjjjjjjjjjz___zzjjjjjjjjj____IIIIIIIIIIII
jjjjjjjjjjjjjjjjjjjjjjjjjjzzjjjjjjjjjjjjj___IIIIIIIIIIII
jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj___IIIIIIIIIIII
jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj____IIIIIIIIIIII
jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjl____wIIIIIIIIIIIII
ljjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjll_____wIIIIIIIIIIIIIIN
___lljjjjjjjjjjjjjjjjjjjjjjjjjjjz____wIIIIIIIIIIIIINN___
______lljjjjjjjjjjjjjjjjjjjjjjjjjz___NIIIIIIIIIINN______
__________lljjjjjjjjjjjjjjjjjjjjjjj____IIIIIIN__________
_____________lljjjjjjjjjjjjjjjjjjjjj____NNN_____________
_________________lljjjjjjjjjjjjjjjjjj___________________
____________________lljjjjjjjjjjjjll____________________
________________________ljjjjjjl________________________
}

