sprite $connect [64x64/16] {
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA5555AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAA555555AAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAA5555555555AAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAA55555555555556AAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAA555555555555555556AAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAA55555555555555555555AAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAA555555555555555555555555AAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAA6555555555555555555555555556AAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAA955555555555555555555555555559AAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAABAAA555555555555555555555555555555AAAAAAAAAAAAAAA
AAAAAAAAAAAAABBBAAAA5555555555555555555555555555555AAAAAAAAAAAAA
AAAAAAAAAAAABBBBBAAA55555AAAAAA6555555555555555555555AAAAAAAAAAA
AAAAAAAAAABBBBBBBAAAA56AAAAAAAAAA555555555555555555555AAAAAAAAAA
AAAAAAAABBBBBBBBBBAAAAAAAAAAAAAAAA5555555555555555555555AAAAAAAA
AAAAAAABBBBBBBBBBBBAAAAAABBBBBBAAA5555555555555555555555AAAAAAAA
AAAAAAABBBBBBBBBBBBAAAABBBBBBBBBAAA555555555555555555555AAAAAAAA
AAAAAAABBBBBBBBBBBBBAABBBBBBBBBBAAA555555555555555555555AAAAAAAA
AAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBAAA555555555555555555555AAAAAAAA
AAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBAAA555555555555555555555AAAAAAAA
AAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBAAA555555555555555555555AAAAAAAA
AAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBAAA555555555555555555555AAAAAAAA
AAAAAAABBBBBBBBBBBBBBBBBBBBBBBBAAA5555555555555555555555AAAAAAAA
AAAAAAABBBBBBBBBBBBBBBBBBBBBBBAAAA5555555555555555555555AAAAAAAA
AAAAAAABBBBBBBBBBBBBBBBBBBBBAAAAA55555555555555555555555AAAAAAAA
AAAAAAABBBBBBBBBBBBBBBBBBBAAAAA5555555555555555555555555AAAAAAAA
AAAAAAABBBBBBBBBBBBBBBBBBAAAAA55555555555555555555555555AAAAAAAA
AAAAAAABBBBBBBBBBBBBBBBBBBAAA555555555555555555555555555AAAAAAAA
AAAAAAABBBBBBBBBBBBBBBBBBBAAA555555555555555555555555555AAAAAAAA
AAAAAAABBBBBBBBBBBBBBBBBBBBAAA55555555555555555555555555AAAAAAAA
AAAAAAABBBBBBBBBBBBBBBBBBBBAAAA55555AAAAA555555555555555AAAAAAAA
AAAAAAABBBBBBBBBBBBBBBBBBBBBAAA555AAAAAAAAA5555555555555AAAAAAAA
AAAAAAABBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAAAAAAA555555555555AAAAAAAA
AAAAAAABBBBBBBBBBBBBBBBBBBBBBAAAAAAAABBBAAAAA55555555555AAAAAAAA
AAAAAAABBBBBBBBBBBBBBBBBBBBBBBAAAAABBBBBBBAAA55555555555AAAAAAAA
AAAAAAABBBBBBBBBBBBBBBBBBBBBBBAAABBBBBBBBBAAAA5555555555AAAAAAAA
AAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAA5555555555AAAAAAAA
AAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAA5555555555AAAAAAAA
AAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAA5555555555AAAAAAAA
AAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAA5555555555AAAAAAAA
AAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAA55555555555AAAAAAAA
AAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAA55555555555AAAAAAAA
AAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAA555555555555AAAAAAAA
AAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAA5555555555555AAAAAAAA
AAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBAAAAA5555555555555AAAAAAAAAA
AAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBAAAA5555555555555AAAAAAAAAAA
AAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBAAA55555555555AAAAAAAAAAAAA
AAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBAAA655555555AAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBAAA5555559AAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBAAAA5555AAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBAAA55AAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
}


!define SITECORE_CONNECT(alias) PUML_ENTITY(component,SITECORE_COLOR,connect,alias,connect)

!definelong SITECORE_CONNECT(alias,label,e_type="component",e_color="SITECORE_COLOR",e_stereo="Sitecore",e_sprite="connect")
PUML_ENTITY(e_type,e_color,e_sprite,label,alias,e_stereo)
!enddefinelong
