sprite $sitecorecontenthubone [51x64/8] {
______________________________________zzzjjjjjjjjjj
__________________________________zzjjjjjjjjjjjjjjj
______________________________zzjjjjjjjjjjjjjjjjjjj
___________________________zzjjjjjjjjjjjjjjjjjjjjjj
_________________________zjjjjjjjjjjjjjjjjjjjjjjjjj
_______________________zjjjjjjjjjjjjjjjjjjjjjjjjjjj
_____________________zjjjjjjjjjjjjjjjjjjjjjjjjjjjjj
____________________jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj
__________________zjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj
_________________zjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjl_
________________jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjl___
_______________jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjl____
______________zjjjjjjjjjjjjjjjjjjjjjjjjjjjjjl______
______________jjjjjjjjjjjjjjjjjjjjjjjjjjjjj________
_____________jjjjjjjjjjjjjjjjjjjjjjjjjjjjl_________
_____________jjjjjjjjjjjjjjjjjjjjjjjjjjjzzzzzzzzzzz
____________jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj
____________jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj
____________jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjl
____________jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj_
____________jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj__
____________jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjl___
____________jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjl_____
____________jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjl_______
___________zjjjjjjjjjjjjjjjjjjjjjjjjjjjjll_________
_________zjjjjjjjjjjjjjjjjjjjjjjjjllll_____________
________zjjjjjjjjjjl_______________________________
______zjjjjjjjjjjl____wwwwwwwwwwwwwwwwwwwwwwwwwwwww
____zjjjjjjjjjjj____wIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
___zjjjjjjjjjjl____wIIIIIIIIIIIIIIIIIIIIIIIIIIIIIN_
_zjjjjjjjjjjl____wIIIIIIIIIIIIIIIIIIIIIIIIIIIIIN___
jjjjjjjjjjjl____IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIN____
}

