sprite $sitecorecontenthub [64x64/8] {
_____________________________wIIIIw_____________________________
__________________________wIIIIIIIIIIw__________________________
_______________________wwIIIIIIIIIIIIIIww_______________________
______________________IIIIIIIIIIIIIIIIIIII______________________
______________________IIIIIIIIIIIIIIIIIIII______________________
______________________IIIIIIIIIIIIIIIIIIII______________________
______________________IIIIIIIIIIIIIIIIIIII______________________
________ww____________IIIIIIIIIIIIIIIIIIII____________zz________
_____wwIIIIw__________IIIIIIIIIIIIIIIIIIII__________zjjjjjzz____
_wwIIIIIIIIIIww_______IIIIIIIIIIIIIIIIIIII_______zzjjjjjjjjjjjzz
IIIIIIIIIIIIIIIIw_____IIIIIIIIIIIIIIIIIIIN_____zjjjjjjjjjjjjjjjj
IIIIIIIIIIIIIIIIIIIw__IIIIIIIIIIIIIIIIIN____zjjjjjjjjjjjjjjjjjjj
IIIIIIIIIIIIIIIIIIIIIwIIIIIIIIIIIIIINN____zjjjjjjjjjjjjjjjjjjjjj
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIN____zjjjjjjjjjjjjjjjjjjjjjjjj
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIN_____zjjjjjjjjjjjjjjjjjjjjjjjjjj
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIN____zjjjjjjjjjjjjjjjjjjjjjjjjjjjjj
NIIIIIIIIIIIIIIIIIIIIIIIIIN_____zjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjl
__NIIIIIIIIIIIIIIIIIIIIIN____zjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjl__
_____NIIIIIIIIIIIIIIIN____zzjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjl_____
_______NIIIIIIIIIIIN____zjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjl_______
__________NIIIIIIII___zjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjl__________
____________NIIIIII___jjjjjjjjjjjjjjjjjjjjjjjjjjjjjl____________
_______________NIII___jjjjjjjjjjjjjjjjjjjjjjjjjjl_______________
_________________NN___jjjjjjjjjjjjjjjjjjjjjjjjl_________________
______________________jjjjjjjjjjjjjjjjjjjjjl____________________
______________________jjjjjjjjjjjjjjjjjjjj______________________
______________________jjjjjjjjjjjjjjjjjjjj______________________
______________________jjjjjjjjjjjjjjjjjjjj______________________
______________________jjjjjjjjjjjjjjjjjjjj______________________
______________________jjjjjjjjjjjjjjjjjjjj______________________
______________________jjjjjjjjjjjjjjjjjjjj______________________
______________________jjjjjjjjjjjjjjjjjjjj______________________
}

