sprite $ [64x64/16] {
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA5555AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAA555555AAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAA55555555AAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAA655555555555AAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAA55555555555555AAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAA5555555555555555AAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAA5555555555555555AAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAA5555555555555555AAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAA5555555555555555AAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAA5555555555555555AAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAA5555555555555555AAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAA5555555555555555AAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAA5555555555555555AAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAA5555555555555555AAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAA5555AAAAAAAAAA5555555555555555AAAAAAAAAABBBBAAAAAAAAAA
AAAAAAAA5555555AAAAAAAAA5555555555555555AAAAAAAAABBBBBBBAAAAAAAA
AAAAAA5555555555AAAAAAAA5555555555555555AAAAAAAABBBBBBBBBBAAAAAA
AAAA55555555555559AAAAAA5555555555555555AAAAAABBBBBBBBBBBBBBAAAA
AAAA555555555555556AAAAA5555555555555555AAAAABBBBBBBBBBBBBBBAAAA
AAAA5555555555555555AAAA5555555555555556AAAABBBBBBBBBBBBBBBBAAAA
AAAA55555555555555555AAA55555555555555AAAAABBBBBBBBBBBBBBBBBAAAA
AAAA5555555555555555556A5555555555555AAAABBBBBBBBBBBBBBBBBBBAAAA
AAAA55555555555555555555555555555555AAAABBBBBBBBBBBBBBBBBBBBAAAA
AAAA555555555555555555555555555555AAAAABBBBBBBBBBBBBBBBBBBBBAAAA
AAAA55555555555555555555555555555AAAAABBBBBBBBBBBBBBBBBBBBBBAAAA
AAAA5555555555555555555555555555AAAABBBBBBBBBBBBBBBBBBBBBBBBAAAA
AAAA555555555555555555555555555AAAABBBBBBBBBBBBBBBBBBBBBBBBBAAAA
AAAA5555555555555555555555555AAAAABBBBBBBBBBBBBBBBBBBBBBBBBBAAAA
AAAA555555555555555555555555AAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAA
AAAAA5555555555555555555555AAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAA
AAAAAA55555555555555555556AAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAA
AAAAAAA55555555555555555AAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAA
AAAAAAAAA55555555555555AAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAA
AAAAAAAAAA555555555555AAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAA
AAAAAAAAAAA555555555AAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAAA
AAAAAAAAAAAA55555555AAAABBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAAAAA
AAAAAAAAAAAAAA555555AAAABBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAAAAAA
AAAAAAAAAAAAAAA55555AAAABBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAA5555AAAABBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAA555AAAABBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAA5AAAABBBBBBBBBBBBBBBBBBBBBAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
}


!define SITECORE_CONTENT-HUB(alias) PUML_ENTITY(component,#EB001A,content-hub,alias,content-hub)

!definelong SITECORE_CONTENT-HUB(alias,label,e_type="component",e_color="#EB001A",e_stereo="Sitecore",e_sprite="content-hub")
PUML_ENTITY(e_type,e_color,e_sprite,label,alias,e_stereo)
!enddefinelong
