sprite $sitecorediscover [80x64/8] {
___________________yaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaay___________________
___________________aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa___________________
___________________aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa___________________
_wwwwwwwwwwwwww____aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa____wwwwwwwwwwwwww_
IIIIIIIIIIIIIII____aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa____IIIIIIIIIIIIIII
IIIIIIIIIIIIIII____aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa____IIIIIIIIIIIIIII
IIIIIIIIIIIIIII____aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa____IIIIIIIIIIIIIII
IIIIIIIIIIIIIII____aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa____IIIIIIIIIIIIIII
IIIIIIIIIIIIIII____aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa____IIIIIIIIIIIIIII
IIIIIIIIIIIIIII____aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa____IIIIIIIIIIIIIII
IIIIIIIIIIIIIII____aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa____IIIIIIIIIIIIIII
IIIIIIIIIIIIIII____aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa____IIIIIIIIIIIIIII
IIIIIIIIIIIIIII____aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa____IIIIIIIIIIIIIII
IIIIIIIIIIIIIII____aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa____IIIIIIIIIIIIIII
IIIIIIIIIIIIIII____aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa____IIIIIIIIIIIIIII
IIIIIIIIIIIIIII____aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa____IIIIIIIIIIIIIII
IIIIIIIIIIIIIII____aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa____IIIIIIIIIIIIIII
IIIIIIIIIIIIIII____aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa____IIIIIIIIIIIIIII
IIIIIIIIIIIIIII____aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa____IIIIIIIIIIIIIII
IIIIIIIIIIIIIII____aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa____IIIIIIIIIIIIIII
IIIIIIIIIIIIIII____aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa____IIIIIIIIIIIIIII
IIIIIIIIIIIIIII____aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa____IIIIIIIIIIIIIII
IIIIIIIIIIIIIII____aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa____IIIIIIIIIIIIIII
IIIIIIIIIIIIIII____aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa____IIIIIIIIIIIIIII
IIIIIIIIIIIIIII____aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa____IIIIIIIIIIIIIII
IIIIIIIIIIIIIII____aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa____IIIIIIIIIIIIIII
IIIIIIIIIIIIIII____aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa____IIIIIIIIIIIIIII
IIIIIIIIIIIIIII____aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa____IIIIIIIIIIIIIII
_NNNNNNNNNNNNNN____aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa____NNNNNNNNNNNNNN_
___________________aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa___________________
___________________aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa___________________
___________________daaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaad___________________
}

