sprite $sitecoreordercloud [59x64/8] {
____________________________________yyaaay_________________
________________________________yyaaaaaaaa_________________
_____________________________yyaaaaaaaaaaa_________________
_________________________yyaaaaaaaaaaaaaaa_________________
______________________yyaaaaaaaaaaaaaaaaaa_________________
__________________yyaaaaaaaaaaaaaaaaaaaaaa_________________
_________________aaaaaaaaaaaaaaaaaaaaaaaaa_________________
aayy_____________aaaaaaaaaaaaaaaaaaaaaaaaa_____________wwII
aaaaayy__________aaaaaaaaaaaaaaaaaaaaaaaaa__________wwIIIII
aaaaaaaaayy______aaaaaaaaaaaaaaaaaaaaaaaad______wwIIIIIIIII
aaaaaaaaaaaayy___aaaaaaaaaaaaaaaaaaaaadd_____wwIIIIIIIIIIII
aaaaaaaaaaaaaaaayaaaaaaaaaaaaaaaaaad_____wwIIIIIIIIIIIIIIII
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaadd_____wwIIIIIIIIIIIIIIIIIII
aaaaaaaaaaaaaaaaaaaaaaaaaaaad_____wwIIIIIIIIIIIIIIIIIIIIIII
aaaaaaaaaaaaaaaaaaaaaaaaad_____wwIIIIIIIIIIIIIIIIIIIIIIIIII
aaaaaaaaaaaaaaaaaaaaaaaaa____IIIIIIIIIIIIIIIIIIIIIIIIIIIIII
aaaaaaaaaaaaaaaaaaaaaaaaa____IIIIIIIIIIIIIIIIIIIIIIIIIIIIII
aaaaaaaaaaaaaaaaaaaaaaaaa____IIIIIIIIIIIIIIIIIIIIIIIIIIIIII
aaaaaaaaaaaaaaaaaaaaaaaaa____IIIIIIIIIIIIIIIIIIIIIIIIIIIIII
aaaaaaaaaaaaaaaaaaaaaaaaa____IIIIIIIIIIIIIIIIIIIIIIIIIIIIII
aaaaaaaaaaaaaaaaaaaaaaaaa____IIIIIIIIIIIIIIIIIIIIIIIIIIIIII
aaaaaaaaaaaaaaaaaaaaaaaaa____IIIIIIIIIIIIIIIIIIIIIIIIIIIIII
aaaaaaaaaaaaaaaaaaaaaaaaa____IIIIIIIIIIIIIIIIIIIIIIIIIIIIII
aaaaaaaaaaaaaaaaaaaaaaaaa____IIIIIIIIIIIIIIIIIIIIIIIIIIIIII
_ddaaaaaaaaaaaaaaaaaaaaaa____IIIIIIIIIIIIIIIIIIIIIIIIIIINN_
_____daaaaaaaaaaaaaaaaaaa____IIIIIIIIIIIIIIIIIIIIIIIIN_____
________ddaaaaaaaaaaaaaaa____IIIIIIIIIIIIIIIIIIIINN________
____________daaaaaaaaaaaa____IIIIIIIIIIIIIIIIIN____________
_______________ddaaaaaaaa____IIIIIIIIIIIIINN_______________
___________________daaaaa____IIIIIIIIIIN___________________
______________________dday___IIIIIINN______________________
_____________________________IIIN__________________________
}

