sprite $ordercloud [64x64/16] {
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBAAAAAAAAAAAAAAAAAAAAAA
AAAAAABBBBAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBAAAAAAAAAAAA5555AAAAAA
AAAAAABBBBBAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBAAAAAAAAAAA55555AAAAAA
AAAAAABBBBBBBAAAAAAAAABBBBBBBBBBBBBBBBBBBBAAAAAAAAA5555555AAAAAA
AAAAAABBBBBBBBBAAAAAAABBBBBBBBBBBBBBBBBBBBAAAAAAA655555555AAAAAA
AAAAAABBBBBBBBBBBAAAAABBBBBBBBBBBBBBBBBBBBAAAAAA5555555555AAAAAA
AAAAAABBBBBBBBBBBBAAAABBBBBBBBBBBBBBBBBBAAAAAA555555555555AAAAAA
AAAAAABBBBBBBBBBBBBBAABBBBBBBBBBBBBBBBBAAAAA65555555555555AAAAAA
AAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAA6555555555555555AAAAAA
AAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAA55555555555555555AAAAAA
AAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAA5555555555555555555AAAAAA
AAAAAABBBBBBBBBBBBBBBBBBBBBBBBBAAAAAA555555555555555555555AAAAAA
AAAAAABBBBBBBBBBBBBBBBBBBBBBBBAAAAA55555555555555555555555AAAAAA
AAAAAABBBBBBBBBBBBBBBBBBBBBBAAAAAA555555555555555555555555AAAAAA
AAAAAABBBBBBBBBBBBBBBBBBBBBBAAAA55555555555555555555555555AAAAAA
AAAAAABBBBBBBBBBBBBBBBBBBBBBAAAA55555555555555555555555555AAAAAA
AAAAAABBBBBBBBBBBBBBBBBBBBBBAAAA55555555555555555555555555AAAAAA
AAAAAABBBBBBBBBBBBBBBBBBBBBBAAAA55555555555555555555555555AAAAAA
AAAAAABBBBBBBBBBBBBBBBBBBBBBAAAA55555555555555555555555555AAAAAA
AAAAAABBBBBBBBBBBBBBBBBBBBBBAAAA55555555555555555555555555AAAAAA
AAAAAABBBBBBBBBBBBBBBBBBBBBBAAAA55555555555555555555555555AAAAAA
AAAAAABBBBBBBBBBBBBBBBBBBBBBAAAA55555555555555555555555555AAAAAA
AAAAAABBBBBBBBBBBBBBBBBBBBBBAAAA55555555555555555555555555AAAAAA
AAAAAABBBBBBBBBBBBBBBBBBBBBBAAAA55555555555555555555555555AAAAAA
AAAAAABBBBBBBBBBBBBBBBBBBBBBAAAA55555555555555555555555555AAAAAA
AAAAAABBBBBBBBBBBBBBBBBBBBBBAAAA55555555555555555555555555AAAAAA
AAAAAABBBBBBBBBBBBBBBBBBBBBBAAAA55555555555555555555555555AAAAAA
AAAAAABBBBBBBBBBBBBBBBBBBBBBAAAA55555555555555555555555555AAAAAA
AAAAAABBBBBBBBBBBBBBBBBBBBBBAAAA55555555555555555555555556AAAAAA
AAAAAAABBBBBBBBBBBBBBBBBBBBBAAAA5555555555555555555555555AAAAAAA
AAAAAAAABBBBBBBBBBBBBBBBBBBBAAAA555555555555555555555555AAAAAAAA
AAAAAAAAAABBBBBBBBBBBBBBBBBBAAAA5555555555555555555555AAAAAAAAAA
AAAAAAAAAAAABBBBBBBBBBBBBBBBAAAA55555555555555555555AAAAAAAAAAAA
AAAAAAAAAAAAAABBBBBBBBBBBBBBAAAA5555555555555555559AAAAAAAAAAAAA
AAAAAAAAAAAAAAAABBBBBBBBBBBBAAAA55555555555555555AAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAABBBBBBBBBBBAAAA555555555555555AAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAABBBBBBBBBAAAA5555555555555AAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAABBBBBBBBAAAA555555555555AAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAABBBBBBAAAA5555555555AAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAABBBBAAAA55555555AAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAABBAAAA555555AAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAABAAAA55555AAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA555AAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA5AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
}


!define SITECORE_ORDERCLOUD(alias) PUML_ENTITY(component,SITECORE_COLOR,ordercloud,alias,ordercloud)

!definelong SITECORE_ORDERCLOUD(alias,label,e_type="component",e_color="SITECORE_COLOR",e_stereo="Sitecore",e_sprite="ordercloud")
PUML_ENTITY(e_type,e_color,e_sprite,label,alias,e_stereo)
!enddefinelong
