sprite $sitecorepersonalize [64x64/8] {
____________________wwwIIIIIIIIIw_______________________________
________________wwIIIIIIIIIIIIIII_______________________________
_____________wIIIIIIIIIIIIIIIIIII_______________________________
__________wwIIIIIIIIIIIIIIIIIIIII_______________________________
________wIIIIIIIIIIIIIIIIIIIIIIII_______________________________
_______IIIIIIIIIIIIIIIIIIIIIIIIII_______________________________
_____wIIIIIIIIIIIIIIIIIIIIIIIIIII_______________________________
____IIIIIIIIIIIIIIIIIIIIIIIINNNN________________________________
___IIIIIIIIIIIIIIIIIIIINN_______________________________________
__IIIIIIIIIIIIIIIIIINN_____zzzzzzzzzz___________________________
_IIIIIIIIIIIIIIIIII_____zjjjjjjjjjjjjjjz________________________
wIIIIIIIIIIIIIIIIN____zjjjjjjjjjjjjjjjjjjj______________________
IIIIIIIIIIIIIIIIN___zjjjjjjjjjjjjjjjjjjjjjjz____________________
IIIIIIIIIIIIIIII___zjjjjjjjjjjjjjjjjjjjjjjjjz___________________
IIIIIIIIIIIIIII____jjjjjjjjjjjjjjjjjjjjjjjjjj___________________
IIIIIIIIIIIIIII____jjjjjjjjjjjjjjjjjjjjjjjjjj______zzzzzzzzzzzz_
IIIIIIIIIIIIIII____jjjjjjjjjjjjjjjjjjjjjjjjjj____jjjjjjjjjjjjjjj
IIIIIIIIIIIIIII____jjjjjjjjjjjjjjjjjjjjjjjjjj____jjjjjjjjjjjjjjj
IIIIIIIIIIIIIII____jjjjjjjjjjjjjjjjjjjjjjjjjl___jjjjjjjjjjjjjjjj
IIIIIIIIIIIIIII____jjjjjjjjjjjjjjjjjjjjjjjjl___zjjjjjjjjjjjjjjjj
NIIIIIIIIIIIIII____jjjjjjjjjjjjjjjjjjjjjjl____zjjjjjjjjjjjjjjjjl
_IIIIIIIIIIIIII____jjjjjjjjjjjjjjjjjjjjl_____jjjjjjjjjjjjjjjjjj_
__IIIIIIIIIIIII____jjjjjjjjjjjjjjllll_____zzjjjjjjjjjjjjjjjjjj__
___IIIIIIIIIIII____jjjjjjjjjjjjjj______zzjjjjjjjjjjjjjjjjjjjj___
____IIIIIIIIIII____jjjjjjjjjjjjjjzzzjjjjjjjjjjjjjjjjjjjjjjjj____
_____NIIIIIIIII____jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjl_____
_______IIIIIIII____jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj_______
________NIIIIII____jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjl________
__________NNIII____jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjll__________
_____________NN____jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjl_____________
___________________jjjjjjjjjjjjjjjjjjjjjjjjjjjll________________
____________________llljjjjjjjjjjjjjjjjjjlll____________________
}

