sprite $personalize [64x64/16] {
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAA555555AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAA6555555555AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAA555555555555AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAA55555555555555AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAA555555555555555AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAA55555555555555555AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAA555555555555555555AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAA5555555555555555555AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAA55555555555555555555AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAA555555555555555555555AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAA5555555555555555555555AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAA95555555555555555555555AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAA55555555555555555555555AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAA65555555555555555555AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAA555555555555555556AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAA55555555555555555AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAA5555555555555556AAAAABBBBBBBBAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAA5555555555555555AAAABBBBBBBBBBBBAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAA555555555555555AAAABBBBBBBBBBBBBBBAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAA55555555555555AAAABBBBBBBBBBBBBBBBBAAAAAAAAAAAAAAAAAAAAAAA
AAAAAA55555555555555AAABBBBBBBBBBBBBBBBBBAAAAAAAAAAAAAAAAAAAAAAA
AAAAA55555555555555AAABBBBBBBBBBBBBBBBBBBBAAAAAAAAAAAAAAAAAAAAAA
AAAAA55555555555555AAABBBBBBBBBBBBBBBBBBBBAAAAAAAAAAAAAAAAAAAAAA
AAAAA5555555555555AAABBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAAAAAAAAAAAAA
AAAAA5555555555555AAABBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAAAAAAAAAAAAA
AAAAA5555555555555AAABBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAAAAAAAAAAAAA
AAAAA5555555555555AAABBBBBBBBBBBBBBBBBBBBBBAAAAABBBBBBBBBBAAAAAA
AAAAA5555555555555AAABBBBBBBBBBBBBBBBBBBBBBAAABBBBBBBBBBBBBAAAAA
AAAAA5555555555555AAABBBBBBBBBBBBBBBBBBBBBBAAABBBBBBBBBBBBBAAAAA
AAAAA5555555555555AAABBBBBBBBBBBBBBBBBBBBBBAAABBBBBBBBBBBBBAAAAA
AAAAA5555555555555AAABBBBBBBBBBBBBBBBBBBBBBAAABBBBBBBBBBBBBAAAAA
AAAAA5555555555555AAABBBBBBBBBBBBBBBBBBBBBAAABBBBBBBBBBBBBBAAAAA
AAAAA5555555555555AAABBBBBBBBBBBBBBBBBBBBBAAABBBBBBBBBBBBBBAAAAA
AAAAAA555555555555AAABBBBBBBBBBBBBBBBBBBBAAABBBBBBBBBBBBBBAAAAAA
AAAAAA555555555555AAABBBBBBBBBBBBBBBBBBBAAAABBBBBBBBBBBBBBAAAAAA
AAAAAA555555555555AAABBBBBBBBBBBBBBBBBBAAAABBBBBBBBBBBBBBBAAAAAA
AAAAAA955555555555AAABBBBBBBBBBBBBBBBBAAAABBBBBBBBBBBBBBBBAAAAAA
AAAAAAA55555555555AAABBBBBBBBBBBBBBBAAAAABBBBBBBBBBBBBBBBAAAAAAA
AAAAAAA55555555555AAABBBBBBBBBBBBAAAAAAABBBBBBBBBBBBBBBBBAAAAAAA
AAAAAAAA5555555555AAABBBBBBBBBBBAAAAAABBBBBBBBBBBBBBBBBBAAAAAAAA
AAAAAAAA6555555555AAABBBBBBBBBBBAAAABBBBBBBBBBBBBBBBBBBBAAAAAAAA
AAAAAAAAA555555555AAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAA
AAAAAAAAAA55555555AAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAA
AAAAAAAAAA65555555AAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAA
AAAAAAAAAAA5555555AAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAAA
AAAAAAAAAAAA555555AAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAAAA
AAAAAAAAAAAAA55555AAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAAAAA
AAAAAAAAAAAAAA5555AAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAAAAAA
AAAAAAAAAAAAAAA555AAABBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAA5AAABBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
}


!define SITECORE_PERSONALIZE(alias) PUML_ENTITY(component,SITECORE_COLOR,personalize,alias,personalize)

!definelong SITECORE_PERSONALIZE(alias,label,e_type="component",e_color="SITECORE_COLOR",e_stereo="Sitecore",e_sprite="personalize")
PUML_ENTITY(e_type,e_color,e_sprite,label,alias,e_stereo)
!enddefinelong
