sprite $sitecoresearch [78x64/8] {
______________________________zzjjjjjjjjjjjjjjjjjjjzzzzzzzzzzzzz______________
___________________________zzjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjz
________________________zzjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj
_____________________yzjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj
___________________zjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj
________________zjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj
_____________zjjjjjjjjjjjjjjjjjllll_________lllljjjjjjjjjjjjjjjjjjjjjjjjjjjjjj
__________zjjjjjjjjjjjjjjjjl______________________lljjjjjjjjjjjjjjjjjjjjjjjjjj
_______zzjjjjjjjjjjjjjjjl_______wwIIIIIIIIIIwww_______ljjjjjjjjjjjjjjjjjjjjjj_
____zzjjjjjjjjjjjjjjjjl_____wwIIIIIIIIIIIIIIIIIIIww_____ljjjjjjjjjjjjjjjjjjjj_
_zzjjjjjjjjjjjjjjjjjl_____wIIIIIIIIIIIIIIIIIIIIIIIIIw_____jjjjjjjjjjjjjjjjjjj_
jjjjjjjjjjjjjjjjjjjl____wIIIIIIIIIIIIIIIIIIIIIIIIIIIII_____ljjjjjjjjjjjjjjjjj_
lllljjjjjjjjjjjjjjl____wIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII_____jjjjjjjjjjjjjjjjj_
___________lllllll_____IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII_____jjjjjjjjjjjjjjj__
______________________IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII_____jjjjjjjjjjjjjjj__
______________________IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII_____jjjjjjjjjjjjjjj__
_______________________IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII_____jjjjjjjjjjjjjjj__
_______________________NIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIN____jjjjjjjjjjjjjjjj__
________________________NIIIIIIIIIIIIIIIIIIIIIIIIIIIIIN____zjjjjjjjjjjjjjjj___
__________________________NIIIIIIIIIIIIIIIIIIIIIIIIIN_____zjjjjjjjjjjjjjjjj___
____________________________NIIIIIIIIIIIIIIIIIIIIIN_____zjjjjjjjjjjjjjjjjjl___
_______________________________NNIIIIIIIIIIIINNN______zjjjjjjjjjjjjjjjjll_____
___________________________________________________zzjjjjjjjjjjjjjjjll________
_____________________________________________zzzjjjjjjjjjjjjjjjjjjl___________
_______________________________________jjjjjjjjjjjjjjjjjjjjjjjjl______________
_______________________________________jjjjjjjjjjjjjjjjjjjjjl_________________
_______________________________________jjjjjjjjjjjjjjjjjjl____________________
_______________________________________jjjjjjjjjjjjjjjll______________________
_______________________________________jjjjjjjjjjjjll_________________________
_______________________________________jjjjjjjjjll____________________________
_______________________________________jjjjjjjl_______________________________
_______________________________________jjjjl__________________________________
}

