sprite $search [64x64/16] {
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAA
AAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAA
AAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAA
AAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAA
AAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAA
AAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAA
AAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAA
AAAAAAAAAAAAAAAABBBBBBBBBBBBBAAAAAAAABBBBBBBBBBBBBBBBBBBBBAAAAAA
AAAAAAAAAAAAAABBBBBBBBBBBBAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBAAAAAA
AAAAAAAAAAAAABBBBBBBBBBBBAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBAAAAAA
AAAAAAAAAAAABBBBBBBBBBBAAAAAA55555556AAAAABBBBBBBBBBBBBBBBAAAAAA
AAAAAAAAAAABBBBBBBBBBBAAAAA555555555555AAAABBBBBBBBBBBBBBBAAAAAA
AAAAAAAAAABBBBBBBBBBBBAAA555555555555555AAAABBBBBBBBBBBBBAAAAAAA
AAAAAAAABBBBBBBBBBBBBAAA55555555555555555AAABBBBBBBBBBBBBAAAAAAA
AAAAAAABBBBBBBBBBBBBAAA5555555555555555555AAABBBBBBBBBBBBAAAAAAA
AAAAAAABBBBBBBBBBBBBAAA55555555555555555559AAABBBBBBBBBBBAAAAAAA
AAAAAAABBBBBBBBBBBBAAA555555555555555555555AAABBBBBBBBBBBAAAAAAA
AAAAAAAAAAABBBBBBBBAAA555555555555555555555AAABBBBBBBBBBBAAAAAAA
AAAAAAAAAAAAAAAAABBAAA5555555555555555555556AAABBBBBBBBBBAAAAAAA
AAAAAAAAAAAAAAAAAAAAAA5555555555555555555555AAABBBBBBBBBBAAAAAAA
AAAAAAAAAAAAAAAAAAAAAA5555555555555555555555AAABBBBBBBBBBAAAAAAA
AAAAAAAAAAAAAAAAAAAAAA5555555555555555555555AAABBBBBBBBBBAAAAAAA
AAAAAAAAAAAAAAAAAAAAAA5555555555555555555555AAABBBBBBBBBBAAAAAAA
AAAAAAAAAAAAAAAAAAAAAA5555555555555555555556AAABBBBBBBBBBAAAAAAA
AAAAAAAAAAAAAAAAAAAAAA555555555555555555555AAABBBBBBBBBBAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAA555555555555555555555AAABBBBBBBBBBAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAA55555555555555555559AAABBBBBBBBBBAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAA5555555555555555555AAABBBBBBBBBBBAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAA55555555555555555AAABBBBBBBBBBBBAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAA655555555555555AAAABBBBBBBBBBBBAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAA555555555556AAAABBBBBBBBBBBBAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAA55555556AAAAABBBBBBBBBBBBAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
}


!define SITECORE_SEARCH(alias) PUML_ENTITY(component,#EB001A,search,alias,search)

!definelong SITECORE_SEARCH(alias,label,e_type="component",e_color="#EB001A",e_stereo="Sitecore",e_sprite="search")
PUML_ENTITY(e_type,e_color,e_sprite,label,alias,e_stereo)
!enddefinelong
