sprite $send [64x64/16] {
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA5AAAABAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA55AAABBAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA555AAAABBAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA555AAAABBBAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA5555AAAABBBBAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA55559AAABBBBBAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA955555AAABBBBBBAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA555555AAABBBBBBBAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA555555AAAABBBBBBBAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA6555555AAAABBBBBBBBAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA5555555AAAABBBBBBBBBAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA65555555AAAABBBBBBBBBBAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA555555556AAABBBBBBBBBBBAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA555555555AAABBBBBBBBBBBBAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAA6555555555AAAABBBBBBBBBBBBAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAA5555555555AAAABBBBBBBBBBBBBAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAA55555555555AAAABBBBBBBBBBBBBBAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAA55555555555AAAABBBBBBBBBBBBBBBAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAA555555555555AAABBBBBBBBBBBBBBBBAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAA5555555555556AAABBBBBBBBBBBBBBBBBAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAA5555555555555AAAABBBBBBBBBBBBBBBBBAAAAAAAAAA
AAAAAAAAAAAAAAAAAA55555555555555AAAABBBBBBBBBBBBBBBBBBAAAAAAAAAA
AAAAAAAAAAAAAAAAA55555555555555AAAABBBBBBBBBBBBBBBBBBBAAAAAAAAAA
AAAAAAAAAAAAAAA955555555555555AAAABBBBBBBBBBBBBBBBBBBBAAAAAAAAAA
AAAAAAAAAAAAAA5555555555555556AAABBBBBBBBBBBBBBBBBBBBBAAAAAAAAAA
AAAAAAAAAAAAA5555555555555556AAAABBBBBBBBBBBBBBBBBBBBBAAAAAAAAAA
AAAAAAAAAAA55555555555555555AAAABBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAA
AAAAAAAAAA55555555555555555AAAABBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAA
AAAAAAAA655555555555555555AAAABBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAA
AAAAAAA555555555555555555AAAABBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAA
AAAAAAA555555555555555555AAABBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAA
AAAAAAAAA555555555555555AAAABBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAA
AAAAAAAAAAA555555555555AAAABBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAA
AAAAAAAAAAAAAA55555555AAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAA
AAAAAAAAAAAAAAAAA5555AAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAA
AAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAA
AAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBAAAAAABBBBBBBBBBBBBBBAAAAAAAAAA
AAAAAAAAAAAAAAAAABBBBBBBBBBBAAAAAAAAAAAAABBBBBBBBBBBBBAAAAAAAAAA
AAAAAAAAAAAAAAAABBBBBBBBBAAAAAAAAAAAAAAAAAAABBBBBBBBBBAAAAAAAAAA
AAAAAAAAAAAAAAAABBBBBAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
}


!define SITECORE_SEND(alias) PUML_ENTITY(component,SITECORE_COLOR,send,alias,send)

!definelong SITECORE_SEND(alias,label,e_type="component",e_color="SITECORE_COLOR",e_stereo="Sitecore",e_sprite="send")
PUML_ENTITY(e_type,e_color,e_sprite,label,alias,e_stereo)
!enddefinelong
