sprite $sitecoresend [64x64/8] {
_____________________________________________________wwIN_____zj
___________________________________________________wIII_____zjjj
________________________________________________wIIIIN_____jjjjj
_____________________________________________wIIIIIN_____zjjjjjj
__________________________________________wwIIIIIN_____zjjjjjjjj
_______________________________________wwIIIIIIIN_____jjjjjjjjjj
_____________________________________wIIIIIIIIN_____zjjjjjjjjjjj
__________________________________wIIIIIIIIIN_____zjjjjjjjjjjjjj
_______________________________wIIIIIIIIIIIN_____jjjjjjjjjjjjjjj
____________________________wIIIIIIIIIIIIN_____zjjjjjjjjjjjjjjjj
_________________________wwIIIIIIIIIIIIN_____zjjjjjjjjjjjjjjjjjj
______________________wwIIIIIIIIIIIIIIN_____jjjjjjjjjjjjjjjjjjjj
____________________wIIIIIIIIIIIIIIIN_____zjjjjjjjjjjjjjjjjjjjjj
_________________wIIIIIIIIIIIIIIIIN_____zjjjjjjjjjjjjjjjjjjjjjjj
______________wIIIIIIIIIIIIIIIIIIN____zjjjjjjjjjjjjjjjjjjjjjjjjj
___________wwIIIIIIIIIIIIIIIIIIN_____zjjjjjjjjjjjjjjjjjjjjjjjjjj
________wwIIIIIIIIIIIIIIIIIIIN_____zjjjjjjjjjjjjjjjjjjjjjjjjjjjj
_____wwIIIIIIIIIIIIIIIIIIIIIF____zjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj
___wIIIIIIIIIIIIIIIIIIIIIIN_____zjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj
wIIIIIIIIIIIIIIIIIIIIIIIN_____zjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj
IIIIIIIIIIIIIIIIIIIIIII_____zjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj
__NNNIIIIIIIIIIIIIIIIN_____zjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj
________NNIIIIIIIIIN_____zjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj
_____________NNNII_____zjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj
______________________zjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj
____________________zjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj
__________________zjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj
_________________zjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj
_______________zjjjjjjjjjjjjjjjjjjllll___lljjjjjjjjjjjjjjjjjjjjj
_____________zjjjjjjjjjjjjjlll________________llljjjjjjjjjjjjjjj
____________jjjjjjjllll_____________________________lljjjjjjjjjj
____________lll__________________________________________llljjjj
}

