sprite $stream [64x64/16] {
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAAAA
AAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAABBBBBBBBBBBBBBBBBBBBBBBAAAA65555555555555555555AAAAAAAAA
AAAAAAAABBBBBBBBBBBBBBBBBBBBBBBAAA5555555555555555555555AAAAAAAA
AAAAAAAABBBBBBBBBBBBBBBBBBBBBBBAAA5555555555555555555555AAAAAAAA
AAAAAAAABBBBBBBBBBBBBBBBBBBBBBBAAA5555555555555555555555AAAAAAAA
AAAAAAAABBBBBBBBBBBBBBBBBBBBBBAAAA5555555555555555555555AAAAAAAA
AAAAAAAABBBBBBBBBBBBBBBBBBBBBBAAAA5555555555555555555555AAAAAAAA
AAAAAAAABBBBBBBBBBBBBBBBBBBBBBAAAA5555555555555555555555AAAAAAAA
AAAAAAAABBBBBBBBBBBBBBBBBBBBBBAAAA5555555555555555555555AAAAAAAA
AAAAAAAABBBBBBBBBBBBBBBBBBBBBBAAAA5555555555555555555555AAAAAAAA
AAAAAAAABBBBBBBBBBBBBBBBBBBBBBAAAA5555555555555555555555AAAAAAAA
AAAAAAAABBBBBBBBBBBBBBBBBBBBBBAAAA5555555555555555555555AAAAAAAA
AAAAAAAABBBBBBBBBBBBBBBBBBBBBBAAAA5555555555555555555555AAAAAAAA
AAAAAAAABBBBBBBBBBBBBBBBBBBBBBAAA95555555555555555555555AAAAAAAA
AAAAAAAABBBBBBBBBBBBBBBBBBBBBBAAA55555555555555555555555AAAAAAAA
AAAAAAAABBBBBBBBBBBBBBBBBBBBBBAAA55555555555555555555555AAAAAAAA
AAAAAAAAABBBBBBBBBBBBBBBBBBBBAAAA55555555555555555555555AAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA555555555555555555555555AAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA5555555555555555555555555AAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAA55555555555555555555555555AAAAAAAAA
AAAAAAAAAAAA55555555555555555555555555AAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAA5555555555555555555555555AAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAA555555555555555555555555AAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAA555555555555555555555556AAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAA55555555555555555555555AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAA55555555555555555555555AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAA55555555555555555555555AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAA55555555555555555555555AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAA55555555555555555555555AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAA55555555555555555555555AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAA55555555555555555555555AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAA55555555555555555555555AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAA55555555555555555555555AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAA55555555555555555555555AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAA55555555555555555555555AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAA55555555555555555555555AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAA55555555555555555555555AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAA6555555555555555555555AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAA55555555555555555555AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
}


!define SITECORE_STREAM(alias) PUML_ENTITY(component,#EB001A,stream,alias,stream)

!definelong SITECORE_STREAM(alias,label,e_type="component",e_color="#EB001A",e_stereo="Sitecore",e_sprite="stream")
PUML_ENTITY(e_type,e_color,e_sprite,label,alias,e_stereo)
!enddefinelong
