sprite $xc [64x64/16] {
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBAAAAAAAAAAAAAA
AA5555555555555AAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBAAAAAAAAAAA
AAA5555555555555AAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBAAAAAAAAA
AAA95555555555555AAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAA
AAAA55555555555555AAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAA
AAAAA5555555555555AAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAA
AAAAAA5555555555555AAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAA
AAAAAAA5555555555555AAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAA
AAAAAAA55555555555555AAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAA
AAAAAAAA5555555555555AAAAABBBBBBBBBBBBBBBAAAAAAABBBBBBBBAAAAAAAA
AAAAAAAAA5555555555555AAAABBBBBBBBBBBBBBAAAAAAAAAABBBBBAAAAAAAAA
AAAAAAAAAA5555555555555AAABBBBBBBBBBBBAAAAAAAAAAAAABBBAAAAAAAAAA
AAAAAAAAAA55555555555556ABBBBBBBBBBBBAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAA5555555555555AABBBBBBBBBBBAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAA5555555555555AABBBBBBBBBAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAA5555555555555ABBBBBBBBBAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAA65555555555555ABBBBBBBAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAA5555555555555AABBBBBBAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAA5555555555555AABBBBBAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAA5555555555555ABBBBBAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAA5555555555555ABBBBBAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAA5555555555555ABBBBBBAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAA5555555555555ABBBBBBBAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAA55555555555556ABBBBBBBAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAA5555555555555ABBBBBBBBBAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAA5555555555555ABBBBBBBBBBAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAA5555555555555AABBBBBBBBBBBAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAA65555555555555ABBBBBBBBBBBBBAAAAAAAAAAAAAABBAAAAAAAAAA
AAAAAAAAAA5555555555555AAABBBBBBBBBBBBBAAAAAAAAAAAABBBBAAAAAAAAA
AAAAAAAAA5555555555555AAAABBBBBBBBBBBBBBAAAAAAAAABBBBBBBAAAAAAAA
AAAAAAAA5555555555555AAAAAABBBBBBBBBBBBBBBAAAAABBBBBBBBBBAAAAAAA
AAAAAAA55555555555555AAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAA
AAAAAA95555555555555AAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAA
AAAAAA5555555555555AAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAA
AAAAA5555555555555AAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAA
AAAA65555555555556AAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAA
AAA95555555555555AAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBAAAAAAAA
AAA5555555555555AAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBAAAAAAAAAA
AA3555555555555AAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
}


!define SITECORE_XC(alias) PUML_ENTITY(component,#EB001A,xc,alias,xc)

!definelong SITECORE_XC(alias,label,e_type="component",e_color="#EB001A",e_stereo="Sitecore",e_sprite="xc")
PUML_ENTITY(e_type,e_color,e_sprite,label,alias,e_stereo)
!enddefinelong
