sprite $xm [64x64/16] {
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAA6556AAAAAAAAAAAAAAAAAAAAAAAAAAAA6556AAAAAAAAAAAAAA
AAAAAAAAAAAAA655556AAAAAAAAAAAAAAAAAAAAAAAAAA555555AAAAAAAAAAAAA
AAAAAAAAAAAA65555555AAAAAAAAAAAAAAAAAAAAAAAA55555556AAAAAAAAAAAA
AAAAAAAAAAA65555555559AAAAAAAAAAAAAAAAAAAA55555555556AAAAAAAAAAA
AAAAAAAAAA6555555555555AAAAAAAAAAAAAAAAAA5555555555556AAAAAAAAAA
AAAAAAAAA65555555555555555AAAAAAAAAAAA55555555555555556AAAAAAAAA
AAAAAAAA655555555555555555555569565555555555555555555556AAAAAAAA
AAAAAAA65555555555555555555555555555555555555555555555555AAAAAAA
AAAAAAA55555555555555555555555555555555555555555555555555AAAAAAA
AAAAAAA55555555555555555555555555555555555555555555555555AAAAAAA
AAAAAAA55555555555555555555555555555555555555555555555555AAAAAAA
AAAAAAAA555555555555555555555555555555555555555555555555AAAAAAAA
AAAAAAAAA5555555555555555555555555555555555555555555555AAAAAAAAA
AAAAAAAAAA55555555555555555555555555555555555555555555AAAAAAAAAA
AAAAAAAAAAA555555555555555556AAAAAA655555555555555555AAAAAAAAAAA
AAAAAAAAAAAA55555555555555AAAAAAAAAAAA55555555555555AAAAAAAAAAAA
AAAAAAAAAAAAA55555555555AAAAAAAAAAAAAAAA55555555555AAAAAAAAAAAAA
AAAAAAAAAAAAAA555555555AAAAAABBBBBBAAAAAA555555555AAAAAAAAAAAAAA
AAAAAAAAAAAAAAA5555555AAAAABBBBBBBBBBBAAAA5555555AAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAA55555AAAABBBBBBBBBBBBBBAAAA55555AAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAA555AAAABBBBBBBBBBBBBBBBAAAA555AAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAA6AAAABBBBBBBBBBBBBBBBBBAAAA6AAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAAAAAAA
AAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAAAAAA
AAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAAAAA
AAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAAAA
AAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAAA
AAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAA
AAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAA
AAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAA
AAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAA
AAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAA
AAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAA
AAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAA
AAAAAAAABBBBBBBBBBBBBBBBBBBBBBBABBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAA
AAAAAAAAABBBBBBBBBBBBBBBBBAAAAAAAAAAAABBBBBBBBBBBBBBBBBAAAAAAAAA
AAAAAAAAAABBBBBBBBBBBBBAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBAAAAAAAAAA
AAAAAAAAAAABBBBBBBBBBBAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBAAAAAAAAAAA
AAAAAAAAAAAABBBBBBBBAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBAAAAAAAAAAAA
AAAAAAAAAAAAABBBBBBAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBAAAAAAAAAAAAA
AAAAAAAAAAAAAABBBBAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
}


!define SITECORE_XM-CLOUD(alias) PUML_ENTITY(component,#EB001A,xm-cloud,alias,xm-cloud)

!definelong SITECORE_XM-CLOUD(alias,label,e_type="component",e_color="#EB001A",e_stereo="Sitecore",e_sprite="xm-cloud")
PUML_ENTITY(e_type,e_color,e_sprite,label,alias,e_stereo)
!enddefinelong
