sprite $xm [64x64/16] {
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
5555555555557AAAAAAAABBBBBBBBBBBBBBAAAAAAAAAAAAAAAABBBBBBBBBBBBB
5555555555555AAAAAAAABBBBBBBBBBBBBBAAAAAAAAAAAAAAABBBBBBBBBBBBBB
A5555555555555AAAAAAABBBBBBBBBBBBBBBAAAAAAAAAAAAAABBBBBBBBBBBBBB
AA5555555555555AAAAAABBBBBBBBBBBBBBBAAAAAAAAAAAAABBBBBBBBBBBBBBB
AA55555555555556AAAAABBBBBBBBBBBBBBBAAAAAAAAAAAAABBBBBBBBBBBBBBB
AAA5555555555555AAAAABBBBBBBBBBBBBBBBAAAAAAAAAAAABBBBBBBBBBBBBBB
AAAA5555555555555AAAABBBBBBBBBBBBBBBBAAAAAAAAAAABBBBBBBBBBBBBBBB
AAAA95555555555555AAABBBBBBBBBBBBBBBBBAAAAAAAAAABBBBBBBBBBBBBBBB
AAAAA65555555555559AABBBBBBBBBBBBBBBBBAAAAAAAAAABBBBBBBBBBBBBBBB
AAAAAA5555555555555AABBBBBBBBBBBBBBBBBAAAAAAAAABBBBBBBBBBBBBBBBB
AAAAAAA5555555555555AABBBBBBBBBBBBBBBBBAAAAAAAABBBBBBBBBBBBBBBBB
AAAAAAA95555555555555ABBBBBBBBBBBBBBBBBAAAAAAAABBBBBBBBBBBBBBBBB
AAAAAAAA5555555555555AABBBBBBBBBBBBBBBBAAAAAAABBBBBBBBBBBBBBBBBB
AAAAAAAAA5555555555555AABBBBBBBBBBBBBBBBAAAAAABBBBBBBBBBBBBBBBBB
AAAAAAAAAA5555555555555ABBBBBBABBBBBBBBBAAAAAABBBBBBBBBBBBBBBBBB
AAAAAAAAAA55555555555556ABBBBBABBBBBBBBBAAAAABBBBBBBBBABBBBBBBBB
AAAAAAAAAAA5555555555555AABBBBABBBBBBBBBBAAAABBBBBBBBBABBBBBBBBB
AAAAAAAAAAAA5555555555555ABBBBAABBBBBBBBBAAAABBBBBBBBAABBBBBBBBB
AAAAAAAAAAAAA5555555555555ABBBAABBBBBBBBBAAABBBBBBBBBAABBBBBBBBB
AAAAAAAAAAAAA5555555555555ABBBAABBBBBBBBBBAABBBBBBBBBAABBBBBBBBB
AAAAAAAAAAAA5555555555555AABBBAAABBBBBBBBBAABBBBBBBBAAABBBBBBBBB
AAAAAAAAAAA55555555555556ABBBBAAABBBBBBBBBABBBBBBBBBAAABBBBBBBBB
AAAAAAAAAAA5555555555555ABBBBBAAABBBBBBBBBBBBBBBBBBBAAABBBBBBBBB
AAAAAAAAAA5555555555555ABBBBBBAAAABBBBBBBBBBBBBBBBBAAAABBBBBBBBB
AAAAAAAAA5555555555555AABBBBBBAAAABBBBBBBBBBBBBBBBBAAAABBBBBBBBB
AAAAAAAA55555555555555ABBBBBBBAAAABBBBBBBBBBBBBBBBBAAAABBBBBBBBB
AAAAAAAA5555555555555ABBBBBBBBAAAAABBBBBBBBBBBBBBBAAAAABBBBBBBBB
AAAAAAA5555555555555AABBBBBBBBAAAAABBBBBBBBBBBBBBBAAAAABBBBBBBBB
AAAAAA5555555555555AABBBBBBBBBAAAAABBBBBBBBBBBBBBAAAAAABBBBBBBBB
AAAAA55555555555555AABBBBBBBBBAAAAAABBBBBBBBBBBBBAAAAAABBBBBBBBB
AAAAA5555555555555AAABBBBBBBBBAAAAAABBBBBBBBBBBBBAAAAAABBBBBBBBB
AAAA5555555555555AAAABBBBBBBBBBAAAAABBBBBBBBBBBBAAAAAAABBBBBBBBB
AAA5555555555555AAAAABBBBBBBBBBAAAAAABBBBBBBBBBBAAAAAAABBBBBBBBB
AA55555555555556AAAAABBBBBBBBBAAAAAAABBBBBBBBBBBAAAAAAABBBBBBBBB
AA5555555555555AAAAAABBBBBBBBBBAAAAAAABBBBBBBBBAAAAAAAABBBBBBBBB
A5555555555555AAAAAAABBBBBBBBBBAAAAAAABBBBBBBBBAAAAAAAABBBBBBBBB
5555555555555AAAAAAAABBBBBBBBBBAAAAAAABBBBBBBBBAAAAAAAABBBBBBBBB
5555555555557AAAAAAAABBBBBBBBBBAAAAAAAABBBBBBBAAAAAAAAABBBBBBBBB
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
}


!define SITECORE_XM(alias) PUML_ENTITY(component,#EB001A,xm,alias,xm)

!definelong SITECORE_XM(alias,label,e_type="component",e_color="#EB001A",e_stereo="Sitecore",e_sprite="xm")
PUML_ENTITY(e_type,e_color,e_sprite,label,alias,e_stereo)
!enddefinelong
