sprite $xp [64x64/16] {
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAA5555555555556AAAAAAAAABBBBBBBBBBBBBBBBBBBBAAAAAAAAAAAAAA
AAAAAAAA55555555555556AAAAAAAABBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAAA
AAAAAAAAA5555555555555AAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAA
AAAAAAAAAA5555555555555AAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAA
AAAAAAAAAA65555555555555AAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAA
AAAAAAAAAAA55555555555555AAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAA
AAAAAAAAAAAA5555555555555AAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAA
AAAAAAAAAAAAA5555555555555AAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAA
AAAAAAAAAAAAA55555555555555AAABBBBBBBBBBAAAAAABBBBBBBBBBBBBAAAAA
AAAAAAAAAAAAAA55555555555555AABBBBBBBBBBAAAAAAAABBBBBBBBBBBAAAAA
AAAAAAAAAAAAAAA5555555555555AABBBBBBBBBBAAAAAAAAABBBBBBBBBBAAAAA
AAAAAAAAAAAAAAAA5555555555555ABBBBBBBBBBAAAAAAAAABBBBBBBBBBAAAAA
AAAAAAAAAAAAAAAA55555555555555ABBBBBBBBBAAAAAAAAABBBBBBBBBBAAAAA
AAAAAAAAAAAAAAAAA55555555555555ABBBBBBBBAAAAAAAAABBBBBBBBBBAAAAA
AAAAAAAAAAAAAAAAAA5555555555555AABBBBBBBAAAAAAAABBBBBBBBBBBAAAAA
AAAAAAAAAAAAAAAAAAA5555555555555ABBBBBBBAAAAAABBBBBBBBBBBBAAAAAA
AAAAAAAAAAAAAAAAAAA95555555555555ABBBBBBBBBBBBBBBBBBBBBBBBAAAAAA
AAAAAAAAAAAAAAAAAAAA65555555555556ABBBBBBBBBBBBBBBBBBBBBBBAAAAAA
AAAAAAAAAAAAAAAAAAAAA5555555555555AABBBBBBBBBBBBBBBBBBBBBAAAAAAA
AAAAAAAAAAAAAAAAAAAAA5555555555555AABBBBBBBBBBBBBBBBBBBBAAAAAAAA
AAAAAAAAAAAAAAAAAAAA65555555555556ABBBBBBBBBBBBBBBBBBBBAAAAAAAAA
AAAAAAAAAAAAAAAAAAA95555555555555ABBBBBBBBBBBBBBBBBBBBAAAAAAAAAA
AAAAAAAAAAAAAAAAAAA5555555555555ABBBBBBBBBBBBBBBBBBBAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAA5555555555555AABBBBBBBBBBBBBBBBAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAA55555555555555ABBBBBBBBAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAA55555555555555ABBBBBBBBBAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAA5555555555555ABBBBBBBBBBAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAA5555555555555AABBBBBBBBBBAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAA55555555555555AABBBBBBBBBBAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAA55555555555555AAABBBBBBBBBBAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAA5555555555555AAAABBBBBBBBBBAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAA5555555555555AAAAABBBBBBBBBBAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAA55555555555555AAAAABBBBBBBBBBAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAA65555555555555AAAAAABBBBBBBBBBAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAA5555555555555AAAAAAABBBBBBBBBBAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAA5555555555555AAAAAAAABBBBBBBBBBAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAA55555555555556AAAAAAAABBBBBBBBBBAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAA5555555555556AAAAAAAAABBBBBBBBBBAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
}


!define SITECORE_XP(alias) PUML_ENTITY(component,#EB001A,xp,alias,xp)

!definelong SITECORE_XP(alias,label,e_type="component",e_color="#EB001A",e_stereo="Sitecore",e_sprite="xp")
PUML_ENTITY(e_type,e_color,e_sprite,label,alias,e_stereo)
!enddefinelong
