!define SITECORE_SYMBOL_COLOR #EB001A

!define TECHN_FONT_SIZE 12

!definelong SC_ENTITY(e_alias, e_label, e_techn, e_descr, e_color, e_sprite, e_stereo)
rectangle "==e_label\n<color:e_color><$e_sprite></color>\n//<size:TECHN_FONT_SIZE>[e_techn]</size>//\n\n e_descr" <<e_stereo>> as e_alias
!enddefinelong
!definelong SC_ENTITY_IMG(e_alias, e_label, e_techn, e_descr, e_img, e_stereo)
rectangle "==e_label\n<img:e_img>\n//<size:TECHN_FONT_SIZE>[e_techn]</size>//\n\n e_descr" <<e_stereo>> as e_alias
!enddefinelong

skinparam defaultTextAlignment center

skinparam component<<Sitecore>> {
    BackgroundColor transparent
    BorderColor transparent
    shadowing false
}
hide <<Sitecore>> stereotype
